### ISSUE TITLE
[win-alpha] feature request : allow to use custom ports

### ISSUE THREAD

**Issue by david-guenault** [kitematic/kitematic#690] opened 2015-06-21 14:27 UTC
like the -p option in docker cli.

**Comment by mchiang0610** [comment] 2015-06-21 18:01
@david-guenault You can go into settings and go into the ports panel to change ports. Thanks! 

Also if you prefer command line, you can use -p option through the Docker CLI button by using Docker command line.

**Comment by jeffdm** [comment] 2015-07-01 01:15
Thanks! Duplicate of #242, closing

**Closed by jeffdm** 2015-07-01 01:15 UTC
