### ISSUE TITLE
Error when try download

### ISSUE THREAD

**Issue by dflorezformaxcl** [kitematic/kitematic#866] opened 2015-07-26 22:40 UTC
Hello,
I received this message when I try to get this image.
Please help me.
Best regards,

Dalmiro

![captura de pantalla 2015-07-26 a las 18 38 43](https://cloud.githubusercontent.com/assets/13478059/8896314/a2fc556c-33c5-11e5-84e3-cc79dea1853b.png)

**Comment by timfallmk** [comment] 2015-07-27 21:41
Hi Dalmiro,
This error means that the tag "latest" is not being used in the repository you tried to download. I can see from the repository that the tags appear to be version numbers:
![screenshot 2015-07-27 at 2 41 04 pm](https://cloud.githubusercontent.com/assets/5316117/8918556/92972154-346d-11e5-844a-c183c263f95c.png)

When you try to launch this container, go to "tags" and select the one you want.

**Comment by dflorezformaxcl** [comment] 2015-07-28 05:03
Great! thank you :-)

2015-07-27 17:42 GMT-04:00 Tim <notifications@github.com>:

> Hi Dalmiro,
> This error means that the tag "latest" is not being used in the repository
> you tried to download. I can see from the repository that the tags appear
> to be version numbers:
> [image: screenshot 2015-07-27 at 2 41 04 pm]
> <https://cloud.githubusercontent.com/assets/5316117/8918556/92972154-346d-11e5-844a-c183c263f95c.png>
>
> When you try to launch this container, go to "tags" and select the one you
> want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/issues/866#issuecomment-125350560>
> .
>



-- 
Dalmiro Florez Llerena
T: +57 3004314632 <%2B56%202%202243%201223> | E-mail:
dflorez@xpectrumtech.com

**Comment by FrenchBen** [comment] 2015-07-28 14:58
thanks @timfallmk for the help - @dflorezformaxcl if the issue is resolved could you close it?

**Closed** 2015-08-12 06:28 UTC
