### ISSUE TITLE
Stuck on "Loading images" screen after launch

### ISSUE THREAD

**Issue by misza222** [kitematic/kitematic#353] opened 2015-04-01 14:03 UTC
When I run kitematic I got stuck on "Loading images" screen. 
![screenshot 2015-04-01 16 01 14](https://cloud.githubusercontent.com/assets/89839/6942556/ab4f2cd2-d888-11e4-9e88-63fd16f2679f.png)

**Comment by jeffdm** [comment] 2015-04-02 02:45
Thanks for the issue!

Are you able to contact https://registry.hub.docker.com?

**Comment by misza222** [comment] 2015-04-02 06:40
Yes, I can access https://registry.hub.docker.com via browser. Actually when I restarted kitematic it pulled lists of images just fine - perhaps adding a timeout and retrying fetching this list would make it more user friendly?

**Comment by jeffdm** [comment] 2015-04-03 15:02
Could just be a one time thing. Will close this for now. Thanks for the issue :smiley:

**Closed by jeffdm** 2015-04-03 15:03 UTC
Labels: bug

**Comment by numanoids** [comment] 2015-06-02 08:58
I know this is closed so not sure if I should create new but I'm having the same problem. No problems accessing the registry via a browser or searching via the CLI but I get the same loading as above. I've restarted Kitematic and my computer to check if something going on and also cleared out all kitematic folders and set up from fresh.

**Comment by ErikNeff** [comment] 2015-06-02 09:06
I'm seeing the same thing - Loading Images spins forever. I too confirmed I can see the registry through the browser and cli, just not through the GUI. 
![image](https://cloud.githubusercontent.com/assets/234436/7932279/fd81cf32-08cb-11e5-9107-1ac595aed8be.png)

**Comment by numanoids** [comment] 2015-06-02 09:09
Ok interestingly, through the docker cli I'm getting this

bash-3.2$ docker pull ubuntu
Pulling repository ubuntu
FATA[0002] Get https://registry-1.docker.io/v1/repositories/library/ubuntu/tags: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: too many redirects
bash-3.2$

This clearly has something to do with virtualbox though as that address is the virtualbox instance IP

**Comment by rainbat** [comment] 2015-06-02 10:50
I'm exactly at the same place - thanks to google i found this thread :)

**Comment by numanoids** [comment] 2015-06-02 11:40
I'm not convinced we can reopen from here. I"ll open a new bug and link to this.

**Comment by victorursu** [comment] 2015-06-02 12:43
Same happens to me - OS X 10.9.5 , Kitematic - 0.6.3

**Comment by flyhawk007** [comment] 2015-06-02 13:59
It's the same to me Mac 10.10.3

**Comment by tojaish** [comment] 2015-06-02 15:49
The Loaders is Spinning infinitely on my Mac 10.10.3. Though i am able to download the images via command line. and yes, i am able to open up the registry at  https://registry.hub.docker.com via the browser. 
![screen shot 2015-06-02 at 11 48 51 am]
![screen shot 2015-06-02 at 11 49 15 am]
![screen shot 2015-06-02 at 11 49 39 am](https://cloud.githubusercontent.com/assets/686450/7940201/77c3220e-091d-11e5-9c5d-5b2110b230ed.png)
(https://cloud.githubusercontent.com/assets/686450/7940196/68248248-091d-11e5-96af-1de1d17e6a3b.png)
(https://cloud.githubusercontent.com/assets/686450/7940188/5ce93b12-091d-11e5-951d-96b378bb18cd.png)

**Comment by lahdekorpi** [comment] 2015-06-02 15:56
Confirming this on 10.9.5.

**Comment by aquinton** [comment] 2015-06-02 16:48
Confirmed on 10.10.3. In addition to not loading any images, I also cannot launch the CLI from a freshly installed state. The app is basically useless at this point.

**Comment by lahdekorpi** [comment] 2015-06-02 17:15
In my installation: pulling, building etc from the docker CLI works just fine.
And the containers show up in the GUI as they should.

Adding containers from the GUI doesn't.

**Comment by mchiang0610** [comment] 2015-06-02 18:26
Hey! Sorry about this. Please restart Kitematic, the recommended images should load now. There was an issue on the API. 
@misza222 @numanoids @lahdekorpi @aquinton @tojaish @flyhawk007 @victorursu @rainbat @ErikNeff

**Comment by lahdekorpi** [comment] 2015-06-02 18:33
Confirmed; working now as usual.

**Comment by sistematico** [comment] 2018-06-03 22:19
Same issue here.

**Comment by hellmachine2000** [comment] 2018-11-01 17:14
Hi folks, is this still a bug? Just installed docker 18.06.1-ce-mac73 and kitematic 0.17.5 on MacOS 10.14 (18A391). Works fine, can search images on https://hub.docker.com/explore/ and via CLI, but kitematic only shows recommended images. A search results in an endless spinning "Loading images".

**Comment by ibouchakour** [comment] 2018-11-05 15:10
the same problem in ubuntu 18.04

**Comment by tmcf** [comment] 2018-11-07 11:28
Same Loading images forever on MacOS 10.14.1, docker 18.06.1-ce-mac73. Kitematic 0.17.5.

Kitematic will also not launch from docker menu (Kitematic is installed in Applications.), has to be launched directly.

**Comment by kiruto** [comment] 2018-11-07 13:47
Same issue on Windows 10

**Comment by kpheasey** [comment] 2018-11-10 15:29
@tmcf I had the same issue. Downgrading to Kitematic to v0.17.3 fixed the problem.  This also fixes the launch from docker, I think docker is looking for 'Kitematic (Beta)' in the application folder and not 'Kitematic'.

**Comment by leye0** [comment] 2018-11-21 15:05
Same here with:
Mac High Sierra 10.13.5
Docker Version 2.0.0.0-mac78 (28905)
Kitematic 0.17.3 (Installed this version because I have the infite "Loading images" bug with 0.17.5)

I've had it for a couple of days now. Since we are 5 having it in the last month after 3 years without problem, I feel like this is no more a "one time" thing.

**Comment by seb0stian** [comment] 2018-11-21 17:54
Same here. Only recommend images and the cli work. Infinite loading
macOS 10.14.1
Kitematic 0.17.5
Docker Version 2.0.0.0-mac78 (28905)

**Comment by RonPimplebut** [comment] 2018-11-23 01:37
Same here. Only recommend images and the cli work. Infinite loading
Os Win10
Kitematic-0.17.5-Windows
Docker CE Version Version 2.0.0.0-win78 (28905)

**Comment by brianmcfadden** [comment] 2018-11-29 06:39
MacOS 10.13.6, Docker version 18.09.0, build 4d60db4, Docker Desktop Version 2.0.0.0-mac78 (28905), Kitematic 0.17.5, fails as described by the bug report.

Downgrading to Kitematic 0.17.3 did fix the issue for me.

One more piece of information: I noticed that the 'docker' command in the shell seemed to be working with two different sets of data, depending on how the shell was started.  When I start bash from the Kitematic 'Open Docker Command-Line Terminal', I run the 'docker images' command and see 2 images (which I had previously installed).  When I start bash from iTerm and run 'docker images' (no kitematic involved), I see a different set of images.

When Kitematic 0.17.3 is installed, I see the same images no matter how bash was started.

**Comment by idurant** [comment] 2018-12-03 16:46
Same problem running Kitematic 0.17.5 on Windows 10. Will downgrade to 0.17.3 and see

**Comment by oliver2221** [comment] 2018-12-05 09:42
same issue here, macOS Mojave 10.14.1
Kitematic 0.17.5
I also have VMware installed ..

**Comment by mbondfusion** [comment] 2018-12-11 19:33
Initial screen shows a list of "Recommended" images, searching show the infinite "Loading..." with spinner.

OS: Windows 10 (current updates)
Docker: v2.0.0.0-win81 (29211), stable, Build: 4271b9e
Kitematic: 0.17.5

**Also behind proxy (I recall that an older version of Kitematic worked fine).

**Comment by ajmarmar** [comment] 2018-12-18 22:36
Hi,
The same problem.
Os Mojave 10.14.2
Docker: 2.0.0.0-mac81 (29211)
Kitematic: 0.17.5.

Regards.

**Comment by serkanozer** [comment] 2019-01-04 12:41
same here High Sierra 10.13.6, docker Version 2.0.0.0-mac81

**Comment by adamo901** [comment] 2019-03-10 11:49
Same here 
OS Mojave 10.14.3
Docker Version 2.0.0.3 (31259)
Kitematic : 0.17.6
regards

**Comment by losectrl** [comment] 2019-07-31 13:47
Version 2.0.0.3 (31259)
OS mojave 10.14.6

login out ; login in ;   resolved!
