### ISSUE TITLE
Better handling of errors caused when creating a container.

### ISSUE THREAD

**Issue by juvesaurabh** [kitematic/kitematic#325] opened 2015-03-24 00:46 UTC
I got a message stating 'There was a problem connecting to the Docker engine in the Virtualbox VM' even though I'm not connected to VPN

**Comment by jeffdm** [comment] 2015-03-24 00:53
Does restarting the app happen to fix it? If not, try removing the VirtualBox VM and then restarting again if you don't have any containers running yet.

Thanks for the issue!

**Comment by juvesaurabh** [comment] 2015-03-24 01:08
Just write that... but still getting the same error.

**Comment by juvesaurabh** [comment] 2015-03-24 01:08
tried*

**Comment by juvesaurabh** [comment] 2015-03-24 19:16
I tried with a different container and it worked but strangely getting this while pulling the centos official image.

**Comment by szilardhuber** [comment] 2015-03-25 16:12
Same issue for me also with the official centos image and an image based on that. Tried restarting Kitematic, logging out from OSX and logging in again, upgrading VirtualBox, removing all VMs but still not working.

**Comment by chaoranxie** [comment] 2015-03-25 19:13
having the same issue, tried remove the vm.

**Comment by jeffdm** [comment] 2015-04-20 21:24
Right now these kinds of errors lock up Kitematic, a good first step is to:
- Show the cause of the error
- Allow the error to be ignored / dismissed

**Comment by mchiang0610** [comment] 2015-05-21 07:12
This should be fixed in the newer builds of Kitematic. Please re-open if you are having issues to let us know!

**Closed by mchiang0610** 2015-05-21 07:12 UTC
Labels: bug, exp/expert
