### ISSUE TITLE
Supply VirtualBox VM options during initial VM setup

### ISSUE THREAD

**Issue by tarapara** [kitematic/kitematic#1111] opened 2015-10-14 13:26 UTC
Hi,

Kitematic is using the 192.168.99.x range for its virtualBox VM which is somehow not possible to change.

I tried following workarounds but no success:
* Re-created the VM via the docker-machine cli and passed the virtualbox-hostonly-cidr values.
* Added virtualbox-hostonly-cidr in the environment variable.

So would it be possible to supply VirtualBox VM options during initial VM setup?

**Comment by FrenchBen** [comment] 2015-10-14 16:41
Currently the address to use is hard-coded, but passing the hostonly-cidr should've allowed it to change.
Is there a reason why that IP does not work for you?

**Comment by mrumpf** [comment] 2015-10-14 18:30
The issue is the corporate VPN solution on our notebooks (I work for the same company). The VPN client allows no other network adapters than a defined set:
* LAN
* WLAN
* VPN Adapter
* Host-Only Network 169.254.0.20/16 (This adapter gets configured with a special package, that our corporate software distrubution tool provides for installation on employee notebooks)
If you create another host-only network adapter, the VPN client starts complaining about the new network adapter until you turn it off :(
Therefore we need to set the parameter ```--virtualbox-hostonly-cidr "169.254.0.20/16" ``` to the ```docker-machine create``` command.
It would be great if you could provide a config file, maybe ```~/.docker/kitematicrc```, where a user can define parameters that are used by kitematic for creating the virtual machine. Or you display any existing docker-machine instances in kitematic without creating a default one.

**Comment by FrenchBen** [comment] 2015-10-14 20:49
@mrumpf Although not integrated into the master yet, this PR https://github.com/kitematic/kitematic/pull/1108 does exactly that.

* Create a `~/.kitematicfg` file
* Add the hostonly info:
```json
{
    "driver": "virtualbox",
    "name": "default",
    "hostonlyCIDR": "169.254.0.20/16"
}
```
* Start kitematic and it will create the virtualbox VM with the proper `virtualbox-hostonly-cidr` flag

**Comment by mrumpf** [comment] 2015-10-15 07:37
Does this also include the ```--engine-env *_PROXY``` to configure the HTTP proxy inside the Docker Machine virtual machine? Without the HTTPS_PROXY, HTTP_PROXY, and NO_PROXY parameters it is not possible in ourt corporate environment to connect to Docker Hub.

**Comment by tarapara** [comment] 2015-10-15 09:13
As per #1108, it seems currently the `~/.kitematicfg` file provides flexibility only for supplying machine's driver options but **not** the engine options. It would be great if it also offers supplying engine's environment options to make Kitematic up and running in the restricted corporate environment.

**Comment by FrenchBen** [comment] 2015-10-15 21:08
@tarapara @mrumpf that's correct no proxy support for now - When I have more free time, I'll look at how this can be implemented.

**Comment by tarapara** [comment] 2015-10-21 15:54
@FrenchBen thanks for your support! We made it working through following trick:
1. Create the **default** vm manually by supplying these additional required parameters like: `--virtualbox-hostonly-cidr` and `--engine-env *_PROXY`.
2.  Start **Kitematic.exe** from **Git Bash** after exporting the proxy settings:
```
export https_proxy=[IP]:[PORT]
export http_proxy=[IP]:[PORT]
```

**Comment by FrenchBen** [comment] 2015-10-21 18:58
@tarapara That's a good work around and will work consistently - Thanks for sharing, I'll add it to the wiki :) - Can you close this issue as it's been resolved?

**Closed** 2015-10-21 19:25 UTC
Labels: feature
