### ISSUE TITLE
Can't remove containers 

### ISSUE THREAD

**Issue by sabuva** [kitematic/kitematic#950] opened 2015-08-18 17:50 UTC
Hi,

Greetings!.

I have three atlassian-confluence containers. Unable to remove them. Getting following errors. 
Please help to remove the 3 containers.

ETIMEDOUT
ETIMEDOUT
connect
192.168.99.100
2376

**Comment by FrenchBen** [comment] 2015-08-19 15:25
close as duplicate of https://github.com/kitematic/kitematic/issues/952

**Closed** 2015-08-24 06:16 UTC
