### ISSUE TITLE
suggestions: stop single container

### ISSUE THREAD

**Issue by simiula** [kitematic/kitematic#432] opened 2015-04-24 13:50 UTC
Using Mac it is to develop things, can be nice to easy start/stop single containers.

**Comment by TeckniX** [comment] 2015-04-24 14:51
Please look through the issues before posting - This is a duplicate of (https://github.com/kitematic/kitematic/issues/426) and has been added to the list of features

**Comment by jeffdm** [comment] 2015-04-28 02:31
Closing for now! In fact, @TeckniX  added this feature just recently! It shipped as part of 0.5.20+. Many thanks to him!

**Closed by jeffdm** 2015-04-28 02:31 UTC
