### ISSUE TITLE
Kitematic hangs @ 99% on "Starting Docker VM"

### ISSUE THREAD

**Issue by djleeam** [kitematic/kitematic#291] opened 2015-03-16 23:21 UTC
![screen shot 2015-03-16 at 4 16 47 pm](https://cloud.githubusercontent.com/assets/761371/6678442/152e0db4-cbf8-11e4-8a6b-b01151abec52.jpg)

OS X Yosemite version 10.10.2

Docker version 1.5.0, build a8a31ef

Oracle VM VirtualBox web service Version 4.3.24
(C) 2007-2015 Oracle Corporation
All rights reserved.
4.3.24r98716

**Comment by holodigm** [comment] 2015-03-17 02:58
+1

**Comment by jeffdm** [comment] 2015-03-17 05:56
Thanks for the issue! This is a duplicate of #236, there's a small workaround there that seems to work for most people. Sorry it got stuck.

**Closed by jeffdm** 2015-03-17 05:56 UTC
Labels: bug

**Comment by holodigm** [comment] 2015-03-17 07:34
Thanks @jeffdm :+1:

**Comment by nevercast** [comment] 2015-09-14 22:23
Leaving this here in case someone stumbles upon it in future.
If the regenerate certs suggestion doesn't work from #236 try the following:

```
docker-machine rm default
docker-machine create default --driver virtualbox
```

In my tests, recreating the default virtual machine manually outside of Kitematic enabled it to work.
