### ISSUE TITLE
UI shows stop button on stopped containers if KM starts with VM off

### ISSUE THREAD

**Issue by jeffdm** [kitematic/kitematic#465] opened 2015-04-30 18:15 UTC

**Comment by TeckniX** [comment] 2015-05-01 16:27
Having trouble replicating this one. Here are my steps:

* Start Kitematic
* Once Kitematic window is up, issue: `VBoxManage controlvm dev savestate`
* Check VM is off `VBoxManage list runningvms`
* Check container window buttons (I get the proper start button)

**Comment by mchiang0610** [comment] 2015-05-21 21:51
This issue should be fixed. Cannot reproduce.

**Closed by mchiang0610** 2015-05-21 21:51 UTC
Labels: bug
