### ISSUE TITLE
Docker CLI with zsh doesn't work on mac os x 

### ISSUE THREAD

**Issue by vincent-herlemont** [kitematic/kitematic#755] opened 2015-07-03 17:03 UTC
Hello,

I try kitematic and docker for the first time but I can't push an sample repository in the hub.
Maybe the button "DOCKER CLI" on left dow has was created for this use.
But when I click on, this open terminal but the casual command appear.
I use zsh for my Terminal, it's maybe the problem.

How can get around this issues ?

**Comment by jeffdm** [comment] 2015-07-03 20:15
If you press the `Docker CLI` button and then type `docker ps`, does it work?

**Comment by vincent-herlemont** [comment] 2015-07-03 20:50
It's freak, see the small test in [this video](https://www.youtube.com/watch?v=gNZuxAHsTeg) ( two shell opens )

**Comment by jeffdm** [comment] 2015-07-03 23:57
@vincent-herlemont got it - definitely a bug. Thanks!

**Comment by jeffdm** [comment] 2015-07-04 00:01
@vincent-herlemont I'm having some trouble reproducing it the zsh bug but it does open two terminals.

Can you provide me the entire command (scroll up after hitting the `Docker CLI` button)?

**Comment by vincent-herlemont** [comment] 2015-07-04 07:14
Ho yes ! sorry, I'don't see that.

Here the command 
```
Last login: Sat Jul  4 09:10:32 on ttys000
bash -c "export PATH='/Users/vincentherlemont/Downloads/Kitematic (Beta).app/Contents/Resources/resources:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' && clear && DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_CERT_PATH=/Users/vincentherlemont/.docker/machine/machines/dev DOCKER_TLS_VERIFY=1 /bin/zsh"
--- ~ » bash -c "export PATH='/Users/vincentherlemont/Downloads/Kitematic (Beta).app/Contents/Resources/resources:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' && clear && DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_CERT_PATH=/Users/vincentherlemont/.docker/machine/machines/dev DOCKER_TLS_VERIFY=1 /bin/zsh"
```

**Comment by vincent-herlemont** [comment] 2015-07-10 10:09
Don't forget this bug please :pray: !

**Comment by tiramisuconpanna** [comment] 2015-07-15 03:16
I seem to have a similar problem: I have previously installed boot2docker and I'm also using oh-my-zsh. When I click on Docker-Cli, I just get to my default terminal. When I use docker, it is connecting to boot2docker, and not the kitematic vm

**Comment by andreis** [comment] 2015-07-15 13:58
The way you wrote that command is very weird. For me this works perfectly:

```
~ export PATH="/opt/homebrew-cask/Caskroom/kitematic/0.7.4/Kitematic (Beta).app/Contents/Resources/resources:$PATH"
~ DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_CERT_PATH=/Users/andreisimionescu/.docker/machine/machines/dev DOCKER_TLS_VERIFY=1
~  docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                     NAMES
1b33d69d21f4        redis:latest        "/entrypoint.sh redi   9 minutes ago       Up 9 minutes        0.0.0.0:32768->6379/tcp   redis
```

I am running zsh, obviously.

**Comment by vincent-herlemont** [comment] 2015-07-15 17:39
Ho thanks you @andreis ! you have give a clew with posting your logs. You use brew for install kitematic, isn't it ? I try that way and now the CLI works perfectly !
Command brew install 
> brew install Caskroom/cask/kitematic

**Comment by andreis** [comment] 2015-07-15 21:11
@vincent-herlemont Aye, I use `brew`, however by doing `brew cask install kitematic` (but probably they're equivalent).

**Comment by phersh** [comment] 2015-07-17 00:58
I think the problem is in the ./resources/terminal script which is called when "DOCKER CLI" button is pressed. Currently that script assumes the use of bash shell and is not compatible with zsh. zsh is very popular shell at least on OS X. I am submitting a pull request which makes the script compatible with both zsh and bash.

**Comment by andreis** [comment] 2015-07-17 07:50
:+1:

**Comment by mchiang0610** [comment] 2015-09-12 00:41
Fixed in toolbox's Quickstart Terminal.

**Closed by mchiang0610** 2015-09-12 00:41 UTC
Labels: bug
