### ISSUE TITLE
dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed.

### ISSUE THREAD

**Issue by demohi** [kitematic/kitematic#959] opened 2015-08-20 02:13 UTC
![image](https://cloud.githubusercontent.com/assets/1209159/9374007/42d64b7c-4723-11e5-8a99-c741f1be556f.png)

mac osx 10.10.4 (14E46)

![image](https://cloud.githubusercontent.com/assets/1209159/9374023/64227bd4-4723-11e5-8e49-9e9dbd859bdf.png)

**Comment by garyrutland** [comment] 2015-08-20 08:48
I'm getting the same issue when running kitematic from downloading the Docker Toolbox.
Any ideas why this is happening?

**Comment by FrenchBen** [comment] 2015-08-20 19:40
Can you both confirm the version of VirtualBox installed on your windows machine?

**Comment by garyrutland** [comment] 2015-08-20 22:22
Not using Windows, using most recent version of OSX. Think it's 10.10.5. It will be what ever version is installed with Docker Toolbox as I didn't have it installed before hand.

**Comment by garyrutland** [comment] 2015-08-21 08:04
On the first attempt at running Kitematic I get this message: Machine IP could not be fetched. Please retry the setup. If this fails please file a ticket on our GitHub repo.
Pressing "Retry setup" comes back with the same message.
When pressing "Retry VM and retry setup" I get the following message: /Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users/<redacted>/.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed.

**Comment by demohi** [comment] 2015-08-21 09:18
Same with @garyrutland

**Comment by toqueteos** [comment] 2015-08-21 14:23
Same here OSX 10.10.4

**Comment by FrenchBen** [comment] 2015-08-21 17:48
@garyrutland @demohi @toqueteos Could you check the system logs as seen in this issue?
https://github.com/docker/machine/issues/1723

Check `/var/log/system.log` for a line that looks like:
```
kernel[0]: vboxdrv: Bad CPU context error at line 4886 in SUPDrv.cpp: EFLAGS.AC is 0!
```

**Comment by nguyentam2211** [comment] 2015-08-22 04:44
Hi @FrenchBen,
I have the same issue like @garyrutland 
Here is what I see in my system.log:
```modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Aug 22 11:38:58 Tams-MacBook-Pro.local GoogleSoftwareUpdateAgent[7206]: 2015-08-22 11:38:58.932 GoogleSoftwareUpdateAgent[7206/0xb0219000] [lvl=3] -[KSAgentApp(KeystoneThread) runKeystonesInThreadWithArg:] Failed to connect to system engine.```

Please let me know if you have any updates.
Thank you very much!

**Comment by nguyentam2211** [comment] 2015-08-22 06:23
I just found a solution from here: https://www.virtualbox.org/ticket/14412
That is install a the latest test build from Virtual Box: https://www.virtualbox.org/wiki/Testbuilds
Hope this can help.

**Comment by garyrutland** [comment] 2015-08-24 09:55
I can confirm I'm getting that line in my logs: 
Aug 24 10:51:45 AM11049 kernel[0]: vboxdrv: Bad CPU context error at line 4886 in SUPDrv.cpp: EFLAGS.AC is 0!

Don't know if it helps or not, but I'm also getting this line soon after:
Aug 24 10:51:45 AM11049 kernel[0]: vboxdrv: Bad CPU context error at line 4912 in SUPDrv.cpp: EFLAGS.AC is 0!

**Comment by pkqk** [comment] 2015-08-24 14:06
I am also getting similar failures:

    24/08/2015 14:43:46.000 kernel[0]: vboxdrv: Bad CPU context error at line 4850 in SUPDrv.cpp: EFLAGS.AC is 0!
    24/08/2015 14:43:46.000 kernel[0]: vboxdrv: Bad CPU context error at line 4884 in SUPDrv.cpp: EFLAGS.AC is 0!

Upgrading to the test release of VirtualBox allowed kitematic to set everything up.

**Comment by garyrutland** [comment] 2015-08-24 15:11
Upgrading to the VirtualBox test build does seem to resolve the issue.

**Comment by FrenchBen** [comment] 2015-08-24 15:39
@garyrutland thanks for the feedback on this working :+1:  - It's difficult for us to push for a 'test' version integration; we'll replicate the test to confirm everything is working and hope that VirtualBox will push it out to the stable branch here soon. 

Link to [Virtualbox](https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#machine-issues-virtualbox) added to wiki.

**Comment by mishgunn** [comment] 2015-09-06 20:01
Updating to latest version of Virtualbox (5.0.2-102096) worked for me as well on OS X 10.9.5.

**Comment by FrenchBen** [comment] 2015-09-08 15:49
thanks for the update @mishgunn :+1:

**Comment by mchiang0610** [comment] 2015-09-11 23:01
Closing to merge with #1029

**Closed by mchiang0610** 2015-09-11 23:01 UTC
