### ISSUE TITLE
500 server error - No command specified

### ISSUE THREAD

**Issue by PorridgeBear** [kitematic/kitematic#434] opened 2015-04-24 18:42 UTC
Have docker installed previously.

Just installed Kitematic Beta. Searched nodejs. Created google nodejs container. Got 500 server error - No command specified - file a ticket. 

Here is a ticket.

**Comment by TeckniX** [comment] 2015-04-24 21:34
Looks like it was a temporary error on the dockerhub - I'm getting a proper download. Can you try again?

**Comment by TeckniX** [comment] 2015-04-28 00:50
Looked a bit more into the issue and it seems to be related to the Dockerfile structure:
```bash
CMD []
ENTRYPOINT ["/nodejs/bin/npm", "start"]
```
When creating a docker container a command is required, which is `bash`. 

Since you mentioned having docker installed before and if you've used this image before, how did you start it? Executing `docker run -t -i google/nodejs` will give you the same `No command specified` error.

**Comment by jeffdm** [comment] 2015-04-28 02:29
Duplicate of #436 so I'll close this for now - please bring the convo there!

Thanks @TeckniX for your feedback on this! It's super awesome.

**Closed by jeffdm** 2015-04-28 02:29 UTC
