### ISSUE TITLE
Fatal Crash on Startup of Kitematic (12" Macbook )

### ISSUE THREAD

**Issue by RickBL99** [kitematic/kitematic#672] opened 2015-06-19 23:00 UTC
On launching Kitematic, at about 9% my MacBook shuts down (black screen of death.)  Totally repeatable.  Here are specs:

  Model Name:	MacBook
  Model Identifier:	MacBook8,1
  Processor Name:	Intel Core M
  Processor Speed:	1.2 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	8 GB
  Boot ROM Version:	MB81.0164.B02
  SMC Version (system):	2.25f85

Yosemite 10.10.3

r

**Comment by mchiang0610** [comment] 2015-06-19 23:26
@RickBL99 Thanks for this. This is an issue that's harder to troubleshoot. We will try to get our hands on the new 12" macbook for testing. 

Thanks!

**Comment by RickBL99** [comment] 2015-06-19 23:38
No worries.  Good luck.  Will try on different machine.

r


> On Jun 19, 2015, at 4:26 PM, Michael Chiang <notifications@github.com> wrote:
> 
> @RickBL99 <https://github.com/RickBL99> Thanks for this. This is an issue that's harder to troubleshoot. We will try to get our hands on the new 12" macbook for testing.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/kitematic/kitematic/issues/672#issuecomment-113670552>.
> 

Rick Leckrone
CEO

Corporate Headquarters:
774 Homewillow Ave
Las Vegas, NV 89123

Blend Seattle:
501 East Pine Street
Suite 200
Seattle WA  98122


C:  +1 (702) 808.3182
F:  +1 (702) 966.0464

Web: http://www.blendimages.com <http://www.blendimages.com/>
Twitter: http://twitter.com/blendimages <http://twitter.com/blendimages>
Facebook: http://www.facebook.com/pages/Blend-Images/100390375008 <http://www.facebook.com/pages/Blend-Images/100390375008>
LinkedIn: http://www.linkedin.com/companies/141069/Blend%20Images <http://www.linkedin.com/companies/141069/Blend%20Images>

**Comment by nicklaslof** [comment] 2015-06-29 14:14
Did happen for me too.  Kernel panic log if it helps solving it:

Mon Jun 29 16:04:11 2015

*** Panic Report ***
panic(cpu 0 caller 0xffffff8001017cc2): Kernel trap at 0xffffff810b75c6c0, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x00000001043033e0, CR3: 0x0000000221ca203a, CR4: 0x00000000003627e0
RAX: 0x00000001043033e0, RBX: 0x0000000000000000, RCX: 0x000000000000000a, RDX: 0x0000000000000000
RSP: 0xffffff800d508f50, RBP: 0xffffff800d508f50, RSI: 0x0000000000000001, RDI: 0x0000000000000015
R8:  0x0000000000000000, R9:  0xffffff800d508ea8, R10: 0x00000001043032a0, R11: 0x0000000000000015
R12: 0xffffff800d50d000, R13: 0x0000000000000000, R14: 0xffffff7f8370a0a0, R15: 0xffffff800d508fc0
RFL: 0x0000000000010202, RIP: 0xffffff810b75c6c0, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00000001043033e0, Error code: 0x0000000000000001, Fault CPU: 0x0 SMAP fault

Backtrace (CPU 0), Frame : Return Address
0xffffff800d508c00 : 0xffffff8000f2bda1
0xffffff800d508c80 : 0xffffff8001017cc2
0xffffff800d508e40 : 0xffffff8001034b73
0xffffff800d508e60 : 0xffffff810b75c6c0
0xffffff800d508f50 : 0xffffff810b73d550
0xffffff800d508f70 : 0xffffff810b75afbb
0xffffff800d508fb0 : 0xffffff810b7edb1e
0xffffff810cceb9c0 : 0xffffff810b75b2fd
0xffffff810cceba00 : 0xffffff7f836d9ab5
0xffffff810ccebaa0 : 0xffffff7f836e16d0
0xffffff810ccebb30 : 0xffffff8001180fb9
0xffffff810ccebb80 : 0xffffff800116f7f6
0xffffff810ccebc10 : 0xffffff8001164693
0xffffff810ccebe00 : 0xffffff80013ae84b
0xffffff810ccebe30 : 0xffffff80013ed7c4
0xffffff810ccebf50 : 0xffffff800144ba86
0xffffff810ccebfb0 : 0xffffff8001035376
      Kernel Extensions in backtrace:
         org.virtualbox.kext.VBoxDrv(4.3.18)[22E424AA-7433-7745-C24C-72982B3936F8]@0xffffff7f836d1000->0xffffff7f83727fff

BSD process name corresponding to current thread: VBoxHeadless

Mac OS version:
14D136

Kernel version:
Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64
Kernel UUID: 4B3A11F4-77AA-3D27-A22D-81A1BC5B504D
Kernel slide:     0x0000000000c00000
Kernel text base: 0xffffff8000e00000
__HIB  text base: 0xffffff8000d00000
System model name: MacBookPro12,1 (Mac-E43C1C25D4880AD6)

System uptime in nanoseconds: 145099964167
last loaded kext at 7047741455: org.virtualbox.kext.VBoxNetAdp  4.3.18 (addr 0xffffff7f83735000, size 28672)

**Comment by mchiang0610** [comment] 2015-06-29 20:53
@nicklaslof Is that from the 12" Macbook as well?

**Comment by nicklaslof** [comment] 2015-06-29 21:12
No. a brand new 13" Macbook Pro.

Attached a screenshot with details:

![aboutmac](https://cloud.githubusercontent.com/assets/331622/8418556/4dd7a7d8-1eb4-11e5-89a4-51f41ba3a9aa.png)

**Comment by RickBL99** [comment] 2015-06-29 22:01
This is screen shot of mine.

https://www.dropbox.com/s/mlqm0wygea9rn1a/Screenshot%202015-06-29%2015.00.56.png?dl=0 <https://www.dropbox.com/s/mlqm0wygea9rn1a/Screenshot%202015-06-29%2015.00.56.png?dl=0>

r


> On Jun 29, 2015, at 2:12 PM, Nicklas Löf <notifications@github.com> wrote:
> 
> No. a brand new 13" Macbook Pro.
> 
> Attached a screenshot with details:
> 
>  <https://cloud.githubusercontent.com/assets/331622/8418556/4dd7a7d8-1eb4-11e5-89a4-51f41ba3a9aa.png>
> —
> Reply to this email directly or view it on GitHub <https://github.com/kitematic/kitematic/issues/672#issuecomment-116847685>.
> 

Rick Leckrone
CEO

Corporate Headquarters:
774 Homewillow Ave
Las Vegas, NV 89123

Blend Seattle:
501 East Pine Street
Suite 200
Seattle WA  98122


C:  +1 (702) 808.3182
F:  +1 (702) 966.0464

Web: http://www.blendimages.com <http://www.blendimages.com/>
Twitter: http://twitter.com/blendimages <http://twitter.com/blendimages>
Facebook: http://www.facebook.com/pages/Blend-Images/100390375008 <http://www.facebook.com/pages/Blend-Images/100390375008>
LinkedIn: http://www.linkedin.com/companies/141069/Blend%20Images <http://www.linkedin.com/companies/141069/Blend%20Images>

**Comment by RickBL99** [comment] 2015-06-29 22:02
Screenshot…

https://www.dropbox.com/s/mlqm0wygea9rn1a/Screenshot%202015-06-29%2015.00.56.png?dl=0 <https://www.dropbox.com/s/mlqm0wygea9rn1a/Screenshot%202015-06-29%2015.00.56.png?dl=0>


> On Jun 29, 2015, at 1:53 PM, Michael Chiang <notifications@github.com> wrote:
> 
> @nicklaslof <https://github.com/nicklaslof> Is that from the 12" Macbook as well?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/kitematic/kitematic/issues/672#issuecomment-116843886>.
> 

Rick Leckrone
CEO

Corporate Headquarters:
774 Homewillow Ave
Las Vegas, NV 89123

Blend Seattle:
501 East Pine Street
Suite 200
Seattle WA  98122


C:  +1 (702) 808.3182
F:  +1 (702) 966.0464

Web: http://www.blendimages.com <http://www.blendimages.com/>
Twitter: http://twitter.com/blendimages <http://twitter.com/blendimages>
Facebook: http://www.facebook.com/pages/Blend-Images/100390375008 <http://www.facebook.com/pages/Blend-Images/100390375008>
LinkedIn: http://www.linkedin.com/companies/141069/Blend%20Images <http://www.linkedin.com/companies/141069/Blend%20Images>

**Comment by limbo0312** [comment] 2015-07-30 04:31
Did happen for me too.
Fatal Crash on Startup of Kitematic (12" Macbook ) 

main problem maybe==> libnode.dylib  isn't work on macbook pro 12' device

please fix it as soon as ..

**Comment by jannostern** [comment] 2015-08-10 08:39
Had a similar problem on a OS X Yosemite 10.10.4, the problem is probably related to boot2docker issue:
https://github.com/boot2docker/boot2docker/issues/800

Downloading latest 4.3.x VirtualBox release helped:
https://www.virtualbox.org/wiki/Download_Old_Builds_4_3

**Comment by mchiang0610** [comment] 2015-09-11 23:17
Should be fixed with latest Docker Toolbox by using the latest VirtualBox

**Closed by mchiang0610** 2015-09-11 23:17 UTC
Labels: bug
