### ISSUE TITLE
Please remove container atlassian-confluence-2

### ISSUE THREAD

**Issue by sabuva** [kitematic/kitematic#951] opened 2015-08-18 18:07 UTC
Hi,

I am unable to remove container . Getting following error while removing. Please help deleting the container.
ETIMEDOUT
ETIMEDOUT
connect
192.168.99.100
2376

**Comment by FrenchBen** [comment] 2015-08-19 15:25
close as duplicate of https://github.com/kitematic/kitematic/issues/952

**Closed** 2015-08-24 06:16 UTC
