### ISSUE TITLE
the official fedora image fails to download

### ISSUE THREAD

**Issue by harrymoore** [kitematic/kitematic#728] opened 2015-06-27 13:59 UTC
I see the following error message a few seconds after attempting download:

"an error occurred"
"Server error500No command specified"

Other images download fine

Thanks

**Comment by jeffdm** [comment] 2015-07-01 01:52
Thanks for the issue!

This is a duplicate of #692, closing for now - stay tuned on that thread.

**Closed by jeffdm** 2015-07-01 01:52 UTC
