### ISSUE TITLE
How can I use a folder under /Users but not under /Users/shauncutts

### ISSUE THREAD

**Issue by shaunc** [kitematic/kitematic#731] opened 2015-06-28 05:47 UTC
The default configuration for Kitematic doesn't work for me, as I have /Users/shauncutts linked to another volume (for more space). I have tried to change folder of example to /Users/docker/hello-world, but I get the error message:

> Invalid Directory. Volume directories must be under your Users directory.

The choice I have made is under the /Users directory, so should be compatible with boot2docker. I assume that Kitematic means "your /Users" directory to be ~shauncutts, not /Users, but this won't work due to boot2docker restrictions (given symlink). Can I change the restriction to ~shauncutts, and where?

**Comment by shaunc** [comment] 2015-06-30 13:20
http://stackoverflow.com/a/29983253/435563 may help ... would be nice to know how to point Kitematic at another directory under /Users, though.

**Comment by TeckniX** [comment] 2015-06-30 16:39
The `/Users` volume is the default volume mounted in Virtualbox, and for most users the volumes they'll mount will be within their home directory, hence the warning.

There are 2 checks in place when mounting  a new volume:
* Is it a proper directory
* Is the directory part of the user's home path. 

The SO link will simply add, by command line, what the GUI would allow you to do, which is create a different volume mount point. 

Some flexibility should be given via Kitematic, the issue is how to determine what volumes are mounted in the VM so that things work as they should?

**Comment by shaunc** [comment] 2015-06-30 17:20
@TeckniX -- thanks .. if the warning were simply a warning that would be fine with me. Unfortunately after the warning there is no volume created.

**Comment by TeckniX** [comment] 2015-06-30 18:22
The warning will not allow the volume to be selected.
If you want to create it manually via the Docker CLI, Kitematic should pick up the changes.

**Comment by jeffdm** [comment] 2015-07-01 01:49
Is the folder under /Users a symlink?

**Comment by shaunc** [comment] 2015-07-01 03:29
My regular user is a symlink to another disk, so I’m trying to set up another mount which is (physically) under /Users, but isn’t under ~shauncutts.

**Comment by xkidro** [comment] 2015-07-17 11:06
I really want to know how to point to other folders than /User , symlinks don't work either

**Comment by FrenchBen** [comment] 2015-07-17 17:15
@xkidro Symlinks wouldn't work as Kitematic checks the path of the volume to confirm it's in the 'Users' directory, which matches the VM settings. 
May need to leverage the VM tools to determine what folders are being shared?

**Comment by jeffdm** [comment] 2015-07-29 15:52
Virtual Box shared folders doesn't work with symlinks. I'm going to close this for now - there should be an equivalent issue for [docker-machine](https://github.com/docker/machine)

Thanks!

**Closed by jeffdm** 2015-07-29 15:52 UTC
Labels: bug, mac
