### ISSUE TITLE
Choose ports and ip to use

### ISSUE THREAD

**Issue by thebillkidy** [kitematic/kitematic#164] opened 2015-01-27 18:22 UTC
Currently I do not see an option to forward the ports that I wish, It automatically picks an available port and shows this.

Example:

I want to run nginx on port 80 but It automatically forwards the port through docker to a random port (49155 for me). Maybe add an option so we can change this?

The same goes for the IP, currently it appoints an ip, but It should be possible to pick the ip being used?

And as a last feature request: Volume mounting, are we able to mount our own volumes instead of the predefined ones?

**Comment by jeffdm** [comment] 2015-01-28 16:34
These are awesome requests! Both in the works. Thanks for opening this issue :)

**Comment by tslater** [comment] 2015-03-14 07:39
+1

**Comment by koalalorenzo** [comment] 2015-05-05 09:45
+1 :+1: 
I would like to use localhost instead of the docker/boot2docker machine IP. If that was automatic it would be amazing!

**Comment by RandomMaker** [comment] 2015-05-10 19:45
You can setup port forwarding in VirtualBox so that you can access the containers using localhost.

One thing that would be great is if the mapped Mac Port stayed constant so that I don't have to keep editing the forwarding rules every time the VM restarts.

**Comment by jeffdm** [comment] 2015-05-10 23:52
@RandomMaker thanks for the feedback

**Comment by RandomMaker** [comment] 2015-05-10 23:54
No problem @jeffdm, keep up the great work!

**Comment by gpapin** [comment] 2015-06-19 10:24
@jeffdm Do we have any update on the ability to change the setting for the port forwarding ?

**Comment by clojj** [comment] 2015-06-19 14:17
+1

**Comment by jeffdm** [comment] 2015-06-20 00:43
@gpapin there's work in progress #598 that's close to being merged! Stay tuned!

**Comment by jeffdm** [comment] 2015-07-01 01:19
Duplicate of #242, closing. Stay tuned to #598

**Closed by jeffdm** 2015-07-01 01:19 UTC
Labels: feature

**Comment by yishilin** [comment] 2015-07-18 12:34
This is not released in the version of 0.7.5 MAC, right? I could not find the feature in the 0.7.5 MAC UI.
Correct me pls if it is.
Thanks.

**Comment by ayancey** [comment] 2016-04-13 08:50
+1
