### ISSUE TITLE
Error when trying to install Mailgun/Vulcand

### ISSUE THREAD

**Issue by bradbergeron-us** [kitematic/kitematic#558] opened 2015-05-28 02:53 UTC
While trying to install Mailgun/vulcand image 
![image](https://cloud.githubusercontent.com/assets/8945799/7851784/d0418b50-04c2-11e5-960d-cd42804efabc.png)

Wish I could get more information I am not able to view the logs with this error!

**Comment by mchiang0610** [comment] 2015-05-28 03:00
@bradbergeron-us Thanks for sending this in. This is the first time we've seen this. 

I wasn't able to reproduce this on my end. (The image was downloaded and then the container stopped due to not able to connect to other services this container needs: )

Service exited with error: service start failure: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

**Comment by bradbergeron-us** [comment] 2015-05-28 15:10
yes the image was the Mailgun/vulcand

**Comment by TeckniX** [comment] 2015-05-29 18:05
Same here - Was able to download and install it without any issues and got the same error as @mchiang0610 
`Service exited with error: service start failure: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]`

If you look at the docs, you'll see that the actual Mailgun/vulcand docker instructions are as follow:
```bash
# download vulcand from the trusted build
docker pull mailgun/vulcand:v0.8.0-beta.2

# launch vulcand in a container
docker run -p 8182:8182 -p 8181:8181 mailgun/vulcand:v0.8.0-beta.2 /go/bin/vulcand -apiInterface=0.0.0.0 --etcd=http://172.17.42.1:4001
```

The etcd bit is more than likely what is failing, since Vulcand uses Etcd as a configuration backend (per their doc)
https://vulcand.io/quickstart.html#quick-start

**Comment by mchiang0610** [comment] 2015-09-12 00:45
Seems like a problem with the particular image. Closing

**Closed by mchiang0610** 2015-09-12 00:45 UTC
Labels: bug
