### ISSUE TITLE
Machine IP cannot be fetched

### ISSUE THREAD

**Issue by nathanleclaire** [kitematic/kitematic#615] opened 2015-06-11 02:37 UTC
I'm 90% sure I've seen this issue before, and it's totes our (Machine's) fault.

![screen shot 2015-06-10 at 7 35 42 pm](https://cloud.githubusercontent.com/assets/1476820/8098695/0ca1c070-0fa8-11e5-961f-77c16e118752.png)

Briefly recall speaking to @jeffdm about this earlier... I think we should probably check for an IP address to be available when we start, since this seems to be a race caused by reporting "Running" status without having confirmed an IP has been selected, at least at a glance.  It could be something more insidious, though.

**Comment by nathanleclaire** [comment] 2015-06-11 02:57
Mmm, trying to dupe is tricky.

**Comment by jonashartmann** [comment] 2015-06-19 10:57
Bump. I consistently got this around 5 times in a row. Mac OS version.
It worked after I did the following (which means I have no clue why it worked):
- Run `docker-machine ip` manually on the terminal
- While Kitematic is starting the VM, right click on Virtual Machine instance inside VirtualBox and select to view the logs

**Comment by TsundereChen** [comment] 2015-06-20 10:30
Have same problem here, running Windows 7 SP1 x64,
I've tried Retry, Delete VM and Retry, even stopped my Anti-Virus, but nothing worked.
![2015-06-20 18 27 26](https://cloud.githubusercontent.com/assets/9039893/8266911/38af1e68-177a-11e5-830f-78bfe68c45bb.png)

**Comment by luisrudge** [comment] 2015-06-20 13:11
I'm having this problem on Windows 10 too.

**Comment by jeffdm** [comment] 2015-06-20 13:45
@luisrudge @TsundereChen investigating now - this may be introduced in 0.7.2 for windows - try 0.7.1.

https://github.com/kitematic/kitematic/releases/download/v0.7.1/KitematicSetup-0.7.1-Windows.exe

**Comment by luisrudge** [comment] 2015-06-20 13:47
Trying now

**Comment by luisrudge** [comment] 2015-06-20 13:48
@jeffdm DO I have to run anything to clean the install? like removing a vm?

**Comment by luisrudge** [comment] 2015-06-20 13:57
@jeffdm it stucks in 99%

**Comment by luisrudge** [comment] 2015-06-20 13:58
```
Error: C:\Users\luis\AppData\Local\Kitematic\app-0.7.1\resources\resources\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 kitematic returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="C:\Users\luis\.docker\machine\machines\kitematic\disk.vmdk"...
Creating dynamic image with size 20971520000 bytes (20000MB)...
Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.

Creating dynamic image with size 20971520000 bytes (20000MB)...
Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.

    at C:\Users\luis\AppData\Local\Kitematic\app-0.7.1\resources\app.asar\utils\Util.js:29:18
    at ChildProcess.<anonymous> (C:\Users\luis\AppData\Local\Kitematic\app-0.7.1\resources\app.asar\node_modules\exec\exec.js:91:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:996:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1069:5)
```

**Comment by dragonet** [comment] 2015-06-24 05:01
I met with the same problems: ( Have any guy found out the solution?

**Comment by briandk** [comment] 2015-06-25 01:05
I'm able to duplicate this pretty consistently on Mac OS X 10.10.3

## Steps to Reproduce (Assuming you have no existing VMs)

1. Open Kitematic. Let it do its initial creation of a VM
2. In preferences, check "Shut Down Linux VM on closing Kitematic". I'm not sure this is necessary, but it's how my Kitematic has been configured.
3. Quit Kitematic
4. Verify through VirtualBox that the VM is powered off
5. Launch Kitematic. It will spin up the VM. 
6. Verify that the VM spinup hangs at 99%, then results in the "Machine IP Could Not Be Fetched" error.

## System Info

- MacBook Pro (early 2011)
- OS X 10.10.3
- Kitematic (Beta) 0.7.3
- VirtualBox 4.3.28 r100309
- [Virtual Machine Log](https://gist.github.com/briandk/31002914731e57c20007)

**Comment by percoclap** [comment] 2015-06-27 03:17
UP please.....with win8.1 x64, and kitematic 0.7.4, same thing "Machine IP could not be fetched"
Kitematic is released for Windows but it don't work with any version on any windows OS.......so I don't see the interest for moment....If anyone have a idea or workaround to fix it, it would be great. Thanks

**Comment by srmor** [comment] 2015-06-30 16:20
I didn't get this error before, but since the recent update I have been getting more errors (including this one). It seems to be caused by the fact that I have the "Shut Down Linux VM on closing Kitematic" option selected.

**Comment by geraldus** [comment] 2015-06-30 16:24
Windows 8.1 x64, Kitematic 0.7.4-alpha, VirtualBox 4.3.28, same issue all the time.

**Comment by lodhaayush** [comment] 2015-07-03 10:46
same issue on OSX.
I hit this consistently every time I restart the laptop.
what @jonashartmann said works some times as a temp fix.

**Comment by jackkav** [comment] 2015-07-06 00:26
Also works if you run the VM in virtualbox first then open kitematic.

**Comment by ifuller1** [comment] 2015-07-08 16:36
Constantly see this if 'shutdown vm' is set on mac. Get across 3 different machines.

**Comment by geraldus** [comment] 2015-07-08 17:35
Just to clarify, I have no issues on OS X (10.10), but Windows installation never worked.  One possible reason could be non-ASCII user name (mine have cyrillic chars), but I can't be certain.

**Comment by ChrisCinelli** [comment] 2015-07-13 07:26
I am running 0.7.4 on OS X 10.9.5 and this keeps happening... Delete the VM and recreate from scratch is taking a while...

**Comment by dhcar** [comment] 2015-07-16 18:28
+1, oddly enough kitematic worked the first time I ran it but afterwards it did not

**Comment by dqmota** [comment] 2015-08-13 04:52
I'm using Docker Toolbox 1.8.0a and it seens there's a bug on Windows version.

When I run the command `docker-machine -D ip default`

I could see the port forwarding rule for ssh service inside docker vm as `Forwarding(0)="ssh,tcp,127.0.0.1,49533,,22"`

However, the ssh command (I had to put `C:\Program Files\Docker Toolbox\kitematic\resources\resources` in PATH env) ignores that config and tries to connect allways using port 22. Mac OS version works as expected.

    STDERR:
    Using SSH client type: external
    About to run SSH command:
    ip addr show dev eth1
    &{C:\Program Files\Docker Toolbox\kitematic\resources\resources\ssh.exe [C:\Program     Files\Docker Toolbox\kitematic\resources\resources\ssh.exe -o PasswordAuthentication=no -o   IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i    C:\Users\Fnac\.docker\machine\machines\default\id_rsa -p 22 docker@localhost ip addr show dev   eth1] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
    SSH cmd err, output: exit status 255:
    exit status 255

Anyone know how to workaround this issue?

**Comment by itsNikolay** [comment] 2015-08-23 08:44
+1 same on mac

**Comment by Illizian** [comment] 2015-08-24 14:53
+1 after migrating from boot2docker to Docker Toolbox.

I can see the following error in logs:
```
executing: /usr/local/bin/VBoxManage modifyvm deafult --natpf1 delete ssh
STDOUT:
STDERR: VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
VBoxManage: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at line 1766 of file VBoxManageModifyVM.cpp
```
Which seems to prevent the VM from starting. 

**OS:** Mac OS X 10.10.3 (14D136)
**Docker:** 1.8.1, build d12ea79
**VBox**: 5.0.2r102096

**Comment by dinolupo** [comment] 2015-08-25 14:58
Not working with:
__OS:__ Windows 7 Enterprise 64bit
__VBox:__ 5.0.0
__Docker Toolbox:__ 1.8.1b

**Comment by itsNikolay** [comment] 2015-08-25 18:34
I fixed it downgrading to VirtualBox 4.3
- Remove VirtualBox 5.0
- Download from official site and install VirtualBox 4.3
- Run Toolbox, under Customize button and skip installation of VirtualBox 5.0
Wish it'll help

**Comment by Illizian** [comment] 2015-08-25 18:47
@itsNikolay excellent, good spot. Thank you.

They must've changed something in VBoxManage, but cannot see any hints in the changelog.

**Comment by Morgy93** [comment] 2015-09-04 09:55
Same Problem here on Windows 10 with Docker Toolbox 1.8.1c 
Tried several things, but nothing helped so far.

![kitematic_bug](https://cloud.githubusercontent.com/assets/7961978/9681077/aec2c390-52fb-11e5-83e1-161ae0958936.PNG)

**Comment by mtvee** [comment] 2015-09-11 14:46
Windows 10, I get a 'Cannot rename connection' error from VBox I presume.Works fine on another win 10 machine so idk, Hopefully this is a clue for someone.

**Comment by mchiang0610** [comment] 2015-09-11 23:18
Merging with #1029

**Closed by mchiang0610** 2015-09-11 23:18 UTC
Labels: bug

**Comment by bigbabert** [comment] 2015-10-21 22:08
same error on OS X when try to set other network on VB, rebuild cert and get error.
