### ISSUE TITLE
rethinkdb errors

### ISSUE THREAD

**Issue by chovy** [kitematic/kitematic#331] opened 2015-03-25 03:18 UTC
```
warn: Failed to sync parent directory of "rethinkdb_data" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
Previous message may not have been written to the log file (cannot open or find log file).
warn: Parent directory of log file (/data/rethinkdb_data/log_file) could not be synced. (Invalid argument)
Recursively removing directory /data/rethinkdb_data/tmp
warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
Initializing directory /data/rethinkdb_data
Running rethinkdb 1.16.2+1~0jessie (GCC 4.9.1)...
Running on Linux 3.18.5-tinycore64 x86_64
Loading data from directory /data/rethinkdb_data
warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/metadata.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/metadata.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
warn: Failed to sync parent directory of "/data/rethinkdb_data/metadata" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/auth_metadata.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/auth_metadata.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
warn: Failed to sync parent directory of "/data/rethinkdb_data/auth_metadata" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, 172.17.0.2, ::1, fe80::42:acff:fe11:2%6
Server ready, "4dd49d4ca1fb_d7e" 75c2558b-6b32-482f-be69-bdefcc04596b
warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/ab8508c3-d6e9-4ed0-bbf0-87c232bb974f.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/ab8508c3-d6e9-4ed0-bbf0-87c232bb974f.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
warn: Failed to sync parent directory of "/data/rethinkdb_data/ab8508c3-d6e9-4ed0-bbf0-87c232bb974f" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)```

**Comment by jeffdm** [comment] 2015-03-26 15:16
This must be caused by the VirtualBox filesystem. Keep an eye on similar issue #209

**Comment by jeffdm** [comment] 2015-03-26 17:50
Closing this for now since it will be fixed at the same time & is the same issue as #209.

**Closed by jeffdm** 2015-03-26 17:50 UTC
Labels: bug
