### ISSUE TITLE
try to run mongo db official image

### ISSUE THREAD

**Issue by tru2dagame** [kitematic/kitematic#336] opened 2015-03-26 08:21 UTC
can't start the mongo db image with these error

    2015-03-26T08:03:43.810+0000 I STORAGE  [initandlisten] exception in initAndListen: 98 Unable to create/open lock file: /data/db/mongod.lock errno:13 Permission denied Is a mongod instance already running?, terminating
    2015-03-26T08:03:43.810+0000 I CONTROL  [initandlisten] dbexit:  rc: 100

The permission of these folders are `USERNAME:staff`
Any idea?

**Comment by jeffdm** [comment] 2015-03-26 15:31
Thanks for the issue. Duplicate of #209, so I'll close this for now. Look out for a fix soon!

**Closed by jeffdm** 2015-03-26 15:31 UTC
Labels: bug
