### ISSUE TITLE
Enabling vm shutdown preference when quitting Kitematic does not work all the time. 

### ISSUE THREAD

**Issue by kangman** [kitematic/kitematic#235] opened 2015-03-12 15:53 UTC
When I close kitematic the Virtualbox VM is still running even thought I have enabled Kitematic to shutdown the VM upon quit.

**Comment by mchiang0610** [comment] 2015-03-12 15:55
+1

**Comment by maxx** [comment] 2015-03-18 13:21
+1

**Comment by ninuxio** [comment] 2015-03-26 16:50
+1

**Comment by jeffdm** [comment] 2015-03-27 17:39
The code for shutting down the VM was refactored in 0.5.11 and after a bunch of testing I couldn't reproduce this. Marking it as closed for now, but feel free to reopen.

**Closed by jeffdm** 2015-03-27 17:39 UTC
Labels: bug

**Comment by padyx** [comment] 2015-11-09 09:40
I can still reproduce this issue (Docker toolbox 1.9, Windows 7 x64) on every shutdown.
Shall I open a new issue @jeffdm or can we reopen this one?

**Comment by RVN-BR** [comment] 2016-06-01 16:19
+1... windows 10 latest docker toolbox... Still there.... it just stays "powered on" in virtualbox admin...

**Comment by FrenchBen** [comment] 2016-06-01 23:54
@RVN-BR if you get the latest release from this repo, it should be fixed. Toolbox needs to be updated
