### ISSUE TITLE
Support For EC2 instances.

### ISSUE THREAD

**Issue by jainishshah17** [kitematic/kitematic#323] opened 2015-03-23 20:40 UTC
Please add support which can allow user to login to EC2 instance to deploy Docker containers. By which we can login to EC2 using SSH and deploy and manage containers there.

**Comment by jeffdm** [comment] 2015-03-24 00:51
Hi, thanks for the issue!

This seems to be a duplicate of #231, as `docker-machine` (what Kitematic uses under the hood for vm management) provides ec2 support

**Closed by jeffdm** 2015-03-24 00:51 UTC
