### ISSUE TITLE
Support data volume containers

### ISSUE THREAD

**Issue by Hartimer** [kitematic/kitematic#248] opened 2015-03-12 21:02 UTC
Only host data volumes are supported, which is particularly problematic on Mac.

For example, the [official MySQL container](https://registry.hub.docker.com/_/mysql/) won't run on kitematic due to Mac and Linux filesystem differences.

This is a [boot2docker problem](https://github.com/boot2docker/boot2docker/issues/581) but the only way to get around it is by using [data volume containers](https://docs.docker.com/userguide/dockervolumes/).

No MySQL, no testing :(

**Comment by jeffdm** [comment] 2015-03-12 21:28
Thanks for the issue and your specific use case! This seems to be a duplicate of #209. Closing for now

**Closed by jeffdm** 2015-03-12 21:28 UTC

**Comment by Hartimer** [comment] 2015-03-12 21:30
I didn't search well enough. Sorry about the duplicate and thank you for the quick reply

**Comment by jeffdm** [comment] 2015-03-12 21:32
Totally not a problem! Thanks again for the issue (and details + links)!
