### ISSUE TITLE
Feature Request: Easily add extra docker registries

### ISSUE THREAD

**Issue by aburnett** [kitematic/kitematic#332] opened 2015-03-25 13:38 UTC
A method to specify additional docker registries via the Kitematic UI. This would ultimately add --insecure-registry args to dockerd running in the VM.

**Comment by jeffdm** [comment] 2015-03-26 02:05
Hi there!

Thanks for creating an issue :smiley: . This seems to be a duplicate of #232. Closing for now but feel free to reopen if not. Thanks for the note on the extra flag needed.

**Closed by jeffdm** 2015-03-26 02:05 UTC
Labels: feature
