### ISSUE TITLE
Missing containers

### ISSUE THREAD

**Issue by ankushagarwal** [kitematic/kitematic#153] opened 2015-01-09 01:25 UTC
I have two containers running, but Kitematic shows only one. 

[These](http://pastebin.com/raw.php?i=EYtGgcjj) are my running containers. 
Here is a screenshot :
 
![image](https://cloud.githubusercontent.com/assets/796949/5674178/11a7a078-975b-11e4-8352-81e7bf8754b5.png)

Kitematic version
0.4.4

$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

**Comment by ankushagarwal** [comment] 2015-01-09 01:27
I started a third container (`docker run -d nginx`). It is running, but still does not show up in the Containers tab.

**Comment by jeffdm** [comment] 2015-01-09 19:00
Hi Ankush,

Thanks for checking out Kitematic!

Sorry about the confusion. Kitematic won't show containers without exposed ports. In this case running `docker run -d nginx` doesn't expose any ports. Adding `-p 80:8080` (or whatever ports you're using) should work!

The problem is that the Docker build process creates a bunch of temporary weirdly-named containers, so we used this as a heuristic to hide them.

We're fixing this in 0.5 - instead of hiding containers with no exposed ports, we'll most likely hide containers whose images aren't tagged or something similar.

Hope this helps! Thanks for the issue!

**Comment by ankushagarwal** [comment] 2015-01-09 19:04
Most of the times, I just want to look at the running containers. The exited containers and temporary containers - not so much. If there could be a view within Kitematic which showed me `docker ps`, that'd be great (or a toggle switch in the containers tab which shows all running containers).

Thanks.
Love the UI of Kitematic.

**Comment by jeffdm** [comment] 2015-03-05 18:12
Fixed in 0.5! Kitematic now syncs all container state with the CLI

The only containers that won't be shown are ones created from images without tags. These are probably intermediate containers that exist due to the build process.

**Closed by jeffdm** 2015-03-05 18:12 UTC

**Comment by ankushagarwal** [comment] 2015-03-05 18:27
Thanks!
