### ISSUE TITLE
500 error reported while downloading a container

### ISSUE THREAD

**Issue by verdurin** [kitematic/kitematic#466] opened 2015-05-01 11:12 UTC
I tried running the official Fedora 21 container via Kitematic and a 500 server error - no command specified was reported, even though elsewhere in the application, the container was still listed as 'downloading'.

This is with Kinematic 0.5.23 on OS X 10.10.3.

**Comment by verdurin** [comment] 2015-05-01 12:49
This has also happened with a CentOS container.

**Comment by TeckniX** [comment] 2015-05-01 15:54
Please provided the DockHub links to the containers you were trying to download, so that we can replicate the issue.

Thanks!

**Comment by Elesant** [comment] 2015-05-01 17:09
@verdurin Sorry about that! It's an known issue that images that don't have a starting command will cause an error in Kitematic. See https://github.com/kitematic/kitematic/issues/230

@TeckniX Thank you so much for helping out! :)

**Comment by TeckniX** [comment] 2015-05-01 17:36
No problem @Elesant

**Comment by jeffdm** [comment] 2015-05-03 19:55
Duplicate of #436, will close for now, look out for a fix soon!

Thanks all!

**Closed by jeffdm** 2015-05-03 19:55 UTC
Labels: bug
