### ISSUE TITLE
Feature request - Container linking

### ISSUE THREAD

**Issue by runseb** [kitematic/kitematic#283] opened 2015-03-15 21:25 UTC
Hi, newbie question here, but I am not seeing anything in the settings to be able to link two containers trough the UI ?

**Comment by mchiang0610** [comment] 2015-03-16 16:14
@runseb, you can currently do container linking through the use of environment variables. 

Screenshot attached. 
![env](https://cloud.githubusercontent.com/assets/3325447/6670596/e909aeae-cbd5-11e4-90dc-959705afe3a8.png)

**Comment by gkawka** [comment] 2015-04-29 19:44
is it full linking or its just like connecting from host? If its first option can you post some details? Eventualy is that functionality on some roadmap?

**Comment by gkawka** [comment] 2015-05-03 09:17
@mchiang0610 ?

**Comment by emilkje** [comment] 2015-05-06 06:28
The linking functionality needs some more work. It's a common use-case to link containers, and a vague reference to ENV variables is not that helpful to be honest. The user interface SHOULD clearly indicate how to link containers intuitively, and the documentation is really lacking fundamental information on this subject.

**Comment by ianwalter** [comment] 2015-05-11 21:19
Yea I think this should be re-opened because if you're downloading an official image, lets say an app that requires a database, the app container isn't going to know about the database container. Linking containers is what the container publisher is expecting you to do so environment variables do not help you in this case.

**Comment by mchiang0610** [comment] 2015-05-12 02:31
@gkawka Not yet. At the moment you have to use environment variables. 

There is a pull request for container linking https://github.com/kitematic/kitematic/pull/479. 

Reopening this issue

**Comment by mchiang0610** [comment] 2015-05-12 02:33
This is actually a duplicate of issue 14. Can we move discussion there? https://github.com/kitematic/kitematic/issues/14

Sorry for the confusion on my part. :(

**Closed by mchiang0610** 2015-05-12 02:33 UTC

**Comment by ArondeParon** [comment] 2015-06-17 12:38
I'd really appreciate some explanation regarding linking containers through the use of environment variables in the meantime. I can't find any solid information on this aspect.

**Comment by lmartins** [comment] 2015-09-10 21:50
Would also appreciate any help on linking containers using environment variables. Anything published by now?

**Comment by RVN-BR** [comment] 2015-11-16 16:23
+1... how do you use env variable for linking?

**Comment by kitplummer** [comment] 2015-11-16 17:53
Yup, would be nice to know what the ENV VAR mechanism is.

**Comment by bls20Automic** [comment] 2015-11-27 14:58
+1 for info on linking containers with environment variables, anyone?

**Comment by bls20Automic** [comment] 2015-11-27 15:37
For me, i needed to link my Wordpress container to my sql container, i did this in the end by adding some environment variables which i obtained from the settings area within the sql container.
![screen shot 2015-11-27 at 15 17 29](https://cloud.githubusercontent.com/assets/8006227/11444368/ad607642-951c-11e5-9bcd-3cb402a75157.png)

**Comment by FrenchBen** [comment] 2015-11-30 19:37
This could be solved via the networking feature discussed here:
https://github.com/docker/kitematic/issues/1249

**Comment by jensoleg** [comment] 2015-12-30 12:32
In the meantime you can do the linking in a docker compose yml file and fire it up via the kitematic Docker cli.

**Comment by josedacosta** [comment] 2017-06-13 15:25
+1
It's clearly missing!
A management of the "links", and a management of "composes"

Here is an example of the Synology Docker:
![image](https://user-images.githubusercontent.com/3801119/27090298-174b92d8-505d-11e7-9057-f566fbb59e21.png)
