### ISSUE TITLE
Kitematic 0.7.3, DNS Unable to resolve and download image

### ISSUE THREAD

**Issue by schrepfler** [kitematic/kitematic#713] opened 2015-06-24 09:12 UTC
Get https://index.docker.io/v1/repositories/itszero/zipkin-web/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects

**Comment by karcaw** [comment] 2015-06-24 20:51
same for me.  0.7.2 works fine..

**Comment by jeffdm** [comment] 2015-07-01 01:40
This is a duplicate of #718, merging. There are instructions on how to fix it manually [there](https://github.com/kitematic/kitematic/issues/718#issuecomment-115489049)

**Closed by jeffdm** 2015-07-01 01:40 UTC
