### ISSUE TITLE
There is not all tags available to pull

### ISSUE THREAD

**Issue by iBobik** [kitematic/kitematic#904] opened 2015-08-10 19:18 UTC
In the Kitematic Hub browser there are not all tags what I can see at web:
https://hub.docker.com/_/php/

![Hub web](https://cloud.githubusercontent.com/assets/614232/9181432/46769b54-3fa5-11e5-91e3-1b45e787db0c.PNG)
![Kitematic](https://cloud.githubusercontent.com/assets/614232/9181431/466f29d2-3fa5-11e5-83b6-4330cf3671e5.PNG)

**Comment by mchiang0610** [comment] 2015-08-10 21:12
@iBobik Thanks! I can reproduce on my side.

**Comment by FrenchBen** [comment] 2015-08-10 22:22
The page you are looking at is a simple 'Readme' file, has nothing to do with the available tags. 
If you want to compare tags for tags, then you need to look at the tags page:
https://hub.docker.com/r/library/php/tags/

This isn't a bug, just documentation of non-existing tags.

**Comment by mchiang0610** [comment] 2015-08-10 22:29
Thanks @FrenchBen.  Closing this issue for now.

**Closed by mchiang0610** 2015-08-10 22:29 UTC
Labels: bug, help wanted

**Comment by iBobik** [comment] 2015-08-10 22:33
It is interesting that in manifest there is also 5.6-apache tag:
https://github.com/docker-library/official-images/blob/master/library/php#L35

And this command worked:
docker pull php:5.6-apache



Jan Pobořil

2015-08-11 0:29 GMT+02:00 Michael Chiang <notifications@github.com>:

**Comment by FrenchBen** [comment] 2015-08-11 18:58
@iBobik Looks like a paging situation - we only show the latest as seen on the hub link above. 
There's a similar feature on the search result that is to be implemented.

**Comment by iBobik** [comment] 2015-08-11 23:42
So you agree this is issue, it should be reopened.


Jan Pobořil
http://honza.poboril.cz/

11. 8. 2015 v 20:58, FrenchBen <notifications@github.com>:

**Comment by FrenchBen** [comment] 2015-08-11 23:58
Kitematic displays the exact same information as seen on the website, thus not a true issue, but a feature request yes )

**Comment by iBobik** [comment] 2015-08-12 00:18
Or maybe UX bug, because people expect exactly same tags what can be used with docker cli :-)

Jan Pobořil
http://honza.poboril.cz/

12 Aug 2015 v 01:58, FrenchBen <notifications@github.com>:

**Comment by ganiutomo** [comment] 2015-08-20 10:46
@FrenchBen If Kitematic display the exact information as seen on the website, then it should show all tags available, not just the top 10 tags on the list.

**Comment by FrenchBen** [comment] 2015-08-20 15:15
@ganiutomo As you clearly showed, the default is the 10 results you see there. The url you provided isn't the user-friendly website I mentioned, but the actual API for that image.
 
Changes have been made to allow the page size increase you mentioned (noticed the url is v2?) These are changes that can now be supported in Kitematic.
