### ISSUE TITLE
Abstract and improve VM support

### ISSUE THREAD

**Issue by dinamic** [kitematic/kitematic#322] opened 2015-03-23 20:38 UTC
Hello guys! Kudoz for the project! The idea seem very promising.

At first glance I didn't liked that you are bound to VirtualBox. As we know it is free, but is also slow. Some of the users may have licenses for other virtual machines. For example, I'm keen on having this operating on a VM powered by Parallels Desktop.

One way to abstract this and give more freedom to the end user would be to adopt vagrant. It has consistent interface across different versions and I honestly doubt there's a developer in the world who need a headless VM and does not have vagrant installed.

I know this may sound like a big step, so you may want to postpone it a bit, but I think, ultimately, this is the direction you should be heading towards.

**Comment by jeffdm** [comment] 2015-03-24 00:49
Thanks for the issue and the kind words!

Since we use `docker-machine` under the hood, adding support for other providers is definitely possible. You can track progress on that here: #231

**Comment by jeffdm** [comment] 2015-03-24 00:49
Closing this for now since it's a duplicate of #231

**Closed by jeffdm** 2015-03-24 00:49 UTC
