### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by DBProductions** [kitematic/kitematic#1125] opened 2015-10-20 09:14 UTC
Get https://registry-1.docker.io/v1/repositories/library/redis/tags/latest: net/http: TLS handshake timeout

Happens all the time (tried four times), I ask myself if it's based on my current location or a common problem. Maybe the government of China is blocking this service because your website is also blocked.
The URI https://registry-1.docker.io/v1/repositories/library/redis/tags/latest itself is reachable.
Same behaviour with Nginx image but works fine with boot2docker and docker on command line.

**Comment by ruandao** [comment] 2015-10-20 12:09
get similar issue:

    Get https://registry-1.docker.io/v1/repositories/library/node/tags/latest: net/http: TLS handshake timeout

I am in China, too.

**Comment by ruandao** [comment] 2015-10-20 12:15
I get the same result when I use Japanese vpn(on aws)

**Comment by ruandao** [comment] 2015-10-20 12:26
my download was start, when i delete previous machine:

    docker-machine rm default

**Comment by FrenchBen** [comment] 2015-10-20 17:02
@ruandao Did you take a look at the wiki on setting up a proxy?
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#proxy-issues

Perhaps it can help smooth some of the connection issues.

**Comment by FrenchBen** [comment] 2015-11-05 00:25
Closing due to no further details provided

**Closed by FrenchBen** 2015-11-05 00:25 UTC

**Comment by jppmateus** [comment] 2016-02-23 11:48
Have the same problem in Portugal. I've deleted default machine but the problem persists. Anyone know how to solve this problem?

**Comment by FrenchBen** [comment] 2016-02-24 22:51
@jppmateus did you look at https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#proxy-issues ?

**Comment by leowmjw** [comment] 2016-03-18 08:48
Hit this (from Malaysia) when working with a slightly more complex Docker setup --> https://github.com/openspending/openspending/issues/891

Tried a few time; and each time after it freezes, I have to restart the docker-machine (see steps below) and it continue to works until it fails again.  When it fails, it seems like all network operations do not work any further.

Kitematic / docker-machine needs to be more robust to poor network condition and not die; needing a restart.

To fix, followed the steps in https://github.com/docker/docker/issues/16829; but root cause of this "hang" is unknown.
```
docker-machine restart default
eval $(docker-machine env default)
```

**Comment by vipulswarup** [comment] 2016-12-30 09:40
I did a `"docker logout"` and then a `"docker login"` and reran the command. Problem gone.

**Comment by mathieu-rossignol** [comment] 2017-11-15 10:31
For me a simple "docker logout" (no login afterwards) dit it. Thx @vipulswarup.

**Comment by bruno-serfe** [comment] 2017-11-16 14:37
Hi guys, I've a similar issue, this is the error:

`ERROR: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/19/1934b0b038d1e8bc64c275b2535fbe808477f5702fbd9a437851a24f9b97d15d/data?Expires=1510843446&Signature=cD2XmGfoJ3wWe3Ybs8Mj1Uaie0gpdNBnuWgjSLUl3Att-u0bN2UObR2VQkdK-5oV1ZlO-VkOhpo1Uryw2O0GZv9TL25bS9VKotCUPWKfXPiXD--0~dGy89dXss4sApT68fAJWA5-sQLLFMIMRamAsOH8EQLaYQ2YyJerFQbABso_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.192.59.197:443: i/o timeout`

but also I've got **TLS handshake timeout** too..

Any thoughts about this?

Appreciated in advance.

Thanks,

**Comment by LinShouGui** [comment] 2017-11-29 15:56
I always get the result:TLS handshake timeout

**Comment by inon** [comment] 2017-12-31 05:15
A simple `docker login` and `docker logout` fixed this issue. Should be applicable if you created the machine  without first logging in. I believe docker needs to refresh the registries for proper `docker push` in the future.

**Comment by helmesjo** [comment] 2018-02-06 13:40
The solution @vipulswarup proposed worked for me, even though I was never logged in, and when running `docker login` I just pressed enter and let it fail (`Error: Non-null Username Required`)...
#looksfinetome :)

**Comment by icbd** [comment] 2018-03-23 07:06
如果使用SS时遇到此问题, 请在docker里手动设置代理.
![screen shot 2018-03-23 at 3 04 37 pm](https://user-images.githubusercontent.com/16110928/37815846-9916b4c8-2eab-11e8-94e8-5f4ec30c35ac.png)

**Comment by DlnZH** [comment] 2018-03-25 11:39
@icbd ,请问这个代理。。。是您自己架设的吗？需要用代理是因为 大绿墙 吗？

**Comment by menglong2234** [comment] 2018-03-25 12:53
@DlnZH 只是把端口设置在本机的代理本地端口而已，需要代理的原因大家都知道就没必要说出来了😏
我就是这样解决的。。

**Comment by MarinZhang** [comment] 2018-04-26 02:30
@menglong2234 能不能不要只 show( off ), 说的详细点可好？

**Comment by MarinZhang** [comment] 2018-04-26 02:31
@icbd 说的详细点可好？

**Comment by MarinZhang** [comment] 2018-04-26 07:37
try dockerhub of Chinese version, it can bypass the tls handshake problem:
`$ docker pull myname/myrepo:mytag -->$ docker pull registry.docker-cn.com/myname/myrepo:mytag`
hope my advice will help you

**Comment by notHide** [comment] 2018-05-03 06:35
@MarinZhang Thx ! worked

**Comment by alitrack** [comment] 2018-05-04 02:11
@helmesjo , it works, thanks

**Comment by korya** [comment] 2018-07-09 20:45
I started to experience the issue about 2-3 weeks ago. My observation is that if docker fails to push an image to the registry (in my case it is Docker Hub) at some layer, it **can** keep failing at the same layer. The solution that worked for me is to remove the image and rebuild it from scratch. Note: in my setup, rebuilding an image from scratch always results in a new hash of the generated image.

The error I see:

```
fccbfa2912f0: Layer already exists
Head https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/c9/c91c36f3dddeecb85898a43fe550163a755e570666249265c339820fab0ca89f/data?verify=1531171424-bntwmPUbN8267s1brEWwenzSkvQ%3D: net/http: TLS handshake timeout
```

Docker version:

```
$ docker version
Client:
 Version:      18.05.0-ce
 API version:  1.35 (downgraded from 1.37)
 Go version:   go1.10.2
 Git commit:   f150324
 Built:        unknown-buildtime
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.01.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   03596f5
  Built:        Wed Jan 10 20:13:12 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by PythaGorilla** [comment] 2019-01-03 12:02
I'm in China. Using a vpn solved this problem

**Comment by prusswan** [comment] 2019-01-20 20:38
Setting DNS to `8.8.8.8` worked for me: https://stackoverflow.com/questions/39655314/docker-for-windows-error-pulling-image-configuration-i-o-timeout

**Comment by axeowl** [comment] 2019-02-22 22:35
To be honest, I resolved this issue with a simple restart of Docker

**Comment by runzhliu** [comment] 2019-05-19 02:04
For Chinese users, I recommend this setting as follows:
![image](https://user-images.githubusercontent.com/20874664/57976880-883f4980-7a1d-11e9-9843-2d364c00ca55.png)

**Comment by andrew-aladev** [comment] 2019-06-24 12:17
Hello. I can say how to reproduce it.

```
rc-service docker stop
docker login
rc-service docker start
buildah/docker push
```

And you can fix it with:

```
docker logout
rc-service docker restart
docker login
buildah/docker push
```

**Comment by dhruvgajwa** [comment] 2019-12-17 13:39
Or you can disable the TLS handshake!
Step 1: Right click on docker icon in your system tray
Step 2: CLick on Settings -> General 
Step 3: Check the box with title:  Expose daemon  without TLS

**Comment by DrPride** [comment] 2020-01-31 07:31
win 10 pro + docker desktop
`logout` do solve the problem.

**Comment by lunaryan** [comment] 2020-03-09 01:55
> To be honest, I resolved this issue with a simple restart of Docker

Me, too

**Comment by letmerecall** [comment] 2020-04-09 11:22
try switching your internet connection.

**Comment by SasukeBo** [comment] 2020-05-12 02:31
> I did a `"docker logout"` and then a `"docker login"` and reran the command. Problem gone.

this work, thx

**Comment by pavanmbm** [comment] 2020-05-19 07:22
> I did a `"docker logout"` and then a `"docker login"` and reran the command. Problem gone.

it worked for me as well

**Comment by nayan2** [comment] 2020-06-26 05:29
I was having the same issue. I just configured Manual DNS which is 1.1.1.1. That solves everything for me.
