### ISSUE TITLE
Kitematic doesn't work with versions of VirtualBox 4.2.x or lower

### ISSUE THREAD

**Issue by jeffdm** [kitematic/kitematic#361] opened 2015-04-04 21:35 UTC

**Comment by Phazz** [comment] 2015-04-04 21:40
I had issue on osx with VirtualBox 4.2.16 installed. I could not get the dev vm created properly. Installing VirtualBox 4.3.26 solved the issue.
I did not document the exact errors.
I could try to reproduce that later.

**Comment by conantp** [comment] 2015-04-06 03:07
I had the setup hang at 99% using Virtualbox 4.3.18 - though I may have been impatient, because when I quit Kinematic and opened VirtualBox it looked like the Docker VM was running. In any case, upgrading to VirtualBox 4.3.26 and re-trying solved the problem.

**Comment by jeffdm** [comment] 2015-04-06 15:29
Thanks for the info @Phazz , @conantp

**Comment by jjn2009** [comment] 2015-04-13 19:57
Kitematic hangs with Virtualbox 4.3.20 as well.
Upgrading to 4.3.26 fixed the issue.

**Comment by jeffdm** [comment] 2015-04-14 15:35
@jjn2009 thanks! This is hugely helpful - sorry about the issues with AnyConnect

**Comment by mchiang0610** [comment] 2015-05-22 00:03
@conantp the 99% issue is a machine issue. see #236 

Closing this one for now to merge discussions.

**Closed by mchiang0610** 2015-05-22 00:03 UTC
Labels: bug
