### ISSUE TITLE
Installation problems - No IP address found 4: eth1 / Error creating machine

### ISSUE THREAD

**Issue by otobrglez** [kitematic/kitematic#379] opened 2015-04-16 07:46 UTC
Hey guys!

I'm trying to install Kitematic (Beta) version 0.5.13 on my OS X 10.10.2 - and I get this error. Can anyone please help me to debug / resolve the problem?

```
/Applications/Kitematic (Beta).app/Contents/Resources/app/resources/docker-machine-0.1.0-kitematic-0.5.10 create -d virtualbox --virtualbox-memory 2048 dev returned non zero exit code stdout:

time="2015-04-16T09:37:28+02:00" level="info" msg="Creating CA: /Users/otobrglez/.docker/machine/certs/ca.pem" time="2015-04-16T09:37:28+02:00" level="info" msg="Creating client certificate: /Users/otobrglez/.docker/machine/certs/cert.pem"

time="2015-04-16T09:37:30+02:00" level="info" msg="Downloading boot2docker.iso to /Users/otobrglez/.docker/machine/cache/boot2docker.iso..."

time="2015-04-16T09:37:51+02:00" level="info" msg="Creating SSH key..."

time="2015-04-16T09:37:51+02:00" level="info" msg="Creating VirtualBox VM..."

time="2015-04-16T09:37:59+02:00" level="info" msg="Starting VirtualBox VM..."

time="2015-04-16T09:37:59+02:00" level="info" msg="Waiting for VM to start..."

time="2015-04-16T09:38:51+02:00" level="error" msg="Error creating machine: No IP address found 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000\n link/ether 08:00:27:d8:b7:9b brd ff:ff:ff:ff:ff:ff\n inet6 fe80::a00:27ff:fed8:b79b/64 scope link \n valid_lft forever preferred_lft forever\n"

time="2015-04-16T09:38:51+02:00" level="warning" msg="You will want to check the provider to make sure the machine and associated resources were properly removed."

time="2015-04-16T09:38:51+02:00" level="fatal" msg="Error creating machine" stderr:
```

Cheers!

- Oto

**Comment by timothyjlaurent** [comment] 2015-04-17 22:13
Try this :+1: 
add this to /etc/hosts

```
127.0.0.1 localhost
```
This fixed the problem for me.

**Comment by mchiang0610** [comment] 2015-05-21 07:06
this is a dupe of https://github.com/kitematic/kitematic/issues/221 

Merging the two.

**Closed by mchiang0610** 2015-05-21 07:06 UTC
