### ISSUE TITLE
Error creating container from Kitematic

### ISSUE THREAD

**Issue by LengBinBin** [kitematic/kitematic#488] opened 2015-05-11 09:35 UTC
![2015-05-11 5 34 11](https://cloud.githubusercontent.com/assets/6848970/7562078/f698675e-f803-11e4-9df9-3c7fe0fce6c9.png)
with this and no other useful information...

**Comment by mchiang0610** [comment] 2015-05-11 16:41
@LengBinBin Can you provide more details regarding this? What image did you use?

**Comment by LengBinBin** [comment] 2015-05-12 02:03
python official , centos  official  .

**Comment by mchiang0610** [comment] 2015-05-12 02:13
@LengBinBin, both of these would error in Kitematic. 

CentOS is a base image, and is not handled by Kitematic. (Sorry about this, we should have done a better job informing our users). 

Python official image is not running due to the python script. https://registry.hub.docker.com/u/library/python/ 

For both of them, if you use the whale button within Kitematic to run, they will work. (And then you can configure it)

**Comment by mchiang0610** [comment] 2015-05-12 02:15
Closing this in favor of issue 450 (Better handling of containers / images that require configuration) and issue 485 (Provide warning when creating a container from a base image) 

https://github.com/kitematic/kitematic/issues/450
https://github.com/kitematic/kitematic/issues/485

**Closed by mchiang0610** 2015-05-12 02:15 UTC

**Comment by LengBinBin** [comment] 2015-05-12 02:23
so sad...

**Comment by mchiang0610** [comment] 2015-05-12 23:08
@LengBinBin The issue is still open, it's just a duplicate. (Wanted to merge for better discussion)
