### ISSUE TITLE
VM not closed cleanly when kitematic is configured to shutdown the VM on exit

### ISSUE THREAD

**Issue by outofjungle** [kitematic/kitematic#257] opened 2015-03-13 04:48 UTC
The "DEV" virtualbox VM was still running after the kitematic was closed even when the setting "shutdown linux VM on closing kitematic" was checked.

**Comment by jeffdm** [comment] 2015-03-13 15:07
Thanks for the issue!

**Comment by ChrisChinchilla** [comment] 2015-03-23 15:38
If it's any help I found that unchecking and rechecking the box fixed this.

**Comment by ninuxio** [comment] 2015-03-26 16:54
@ChrisChinchilla same here but it's a one time fix. if you reopen kinematic and close it again the vm stay ON

**Comment by ninuxio** [comment] 2015-03-27 09:09
duplicate with #235 ?

**Comment by jeffdm** [comment] 2015-03-27 17:15
This is a duplicate of #235, thanks @ninuxio

**Closed by jeffdm** 2015-03-27 17:15 UTC
Labels: bug
