### ISSUE TITLE
VM Shutdown does not happen when Kitematic is closed

### ISSUE THREAD

**Issue by mmaio** [kitematic/kitematic#304] opened 2015-03-18 16:59 UTC
I noticed the dev VM in virtual box remains running when Kitematic is closed regardless if the Shutdown Linux VM on closing Kitematic setting is checked or not.

**Comment by jeffdm** [comment] 2015-03-18 18:45
Thanks for the issue! Duplicate of #257

**Closed** 2015-03-18 18:45 UTC
Labels: bug
