### ISSUE TITLE
Kitematic timeout when connecting to VM

### ISSUE THREAD

**Issue by hterhanian** [kitematic/kitematic#143] opened 2014-12-16 16:59 UTC
Kitematic is timing out when it tries to grab ```http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js```. I was able to get JS by loading same link in browser. I am using Cisco AnyConnect v3.1.

### Kitematic Log
```
MacOS hterhanian$ ./Kitematic
[35252:1216/085055:WARNING:dns_config_service_posix.cc(151)] dns_config has unhandled options!
Starting production server
/Users/hterhanian/Library/Application Support/Kitematic/data
MongoDB: 60341
webPort: 60340
2014-12-16T08:50:55.460-0800 [initandlisten] MongoDB starting : pid=35259 port=60341 dbpath=/Users/hterhanian/Library/Application Support/Kitematic/data 64-bit host=L020157POX01
2014-12-16T08:50:55.460-0800 [initandlisten] db version v2.6.3
2014-12-16T08:50:55.460-0800 [initandlisten] git version: 255f67a66f9603c59380b2a389e386910bbb52cb
2014-12-16T08:50:55.460-0800 [initandlisten] build info: Darwin mci-osx108-3.build.10gen.cc 12.3.0 Darwin Kernel Version 12.3.0: Sun Jan  6 22:37:10 PST 2013; root:xnu-2050.22.13~1/RELEASE_X86_64 x86_64 BOOST_LIB_VERSION=1_49
2014-12-16T08:50:55.460-0800 [initandlisten] allocator: system

Starting node child...
2014-12-16T08:50:55.460-0800 [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 60341, unixDomainSocket: { pathPrefix: "/Users/hterhanian/Library/Application Support/Kitematic/data" } }, storage: { dbPath: "/Users/hterhanian/Library/Application Support/Kitematic/data" } }
2014-12-16T08:50:55.460-0800 [initandlisten] journal dir=/Users/hterhanian/Library/Application Support/Kitematic/data/journal
2014-12-16T08:50:55.461-0800 [initandlisten] recover : no journal files present, no recovery needed

2014-12-16T08:50:55.479-0800 [initandlisten] waiting for connections on port 60341

Kitematic started.

2014-12-16T08:50:56.016-0800 [initandlisten] connection accepted from 127.0.0.1:60342 #1 (1 connection now open)

2014-12-16T08:50:56.025-0800 [conn1] end connection 127.0.0.1:60342 (0 connections now open)

2014-12-16T08:50:56.056-0800 [initandlisten] connection accepted from 127.0.0.1:60343 #2 (1 connection now open)

2014-12-16T08:50:56.111-0800 [initandlisten] connection accepted from 127.0.0.1:60344 #3 (2 connections now open)

2014-12-16T08:50:56.112-0800 [initandlisten] connection accepted from 127.0.0.1:60345 #4 (3 connections now open)

2014-12-16T08:50:56.113-0800 [initandlisten] connection accepted from 127.0.0.1:60346 #5 (4 connections now open)
2014-12-16T08:50:56.114-0800 [initandlisten] connection accepted from 127.0.0.1:60347 #6 (5 connections now open)

[35252:1216/085056:INFO:CONSOLE(175)] "Kitematic started.", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (175)
[35252:1216/085057:INFO:CONSOLE(173)] "Performing step 0", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (173)
[35252:1216/085057:INFO:CONSOLE(173)] "Performing step 1", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (173)
[35252:1216/085057:INFO:CONSOLE(173)] "Performing step 2", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (173)
Checking for update...
[35252:1216/085057:INFO:CONSOLE(173)] "Performing step 3", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (173)
Update not available.
[35252:1216/085105:INFO:CONSOLE(173)] "Performing step 4", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (173)
[35252:1216/085105:INFO:CONSOLE(173)] "Setting host IP to: 192.168.59.103", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (173)
[35252:1216/085105:INFO:CONSOLE(173)] "Setup finished.", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (173)
2014-12-16T08:51:55.534-0800 [clientcursormon] mem (MB) res:50 virt:2843
2014-12-16T08:51:55.534-0800 [clientcursormon]  mapped (incl journal view):320
2014-12-16T08:51:55.534-0800 [clientcursormon]  connections:5

[35252:1216/085221:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085223:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085225:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085227:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085229:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085231:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085233:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085235:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085237:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085239:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085241:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085243:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085245:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085247:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085249:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085251:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085253:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085255:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085257:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085259:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085301:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085303:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085305:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085307:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085310:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085312:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085314:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085316:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085318:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085320:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085322:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085324:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085326:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085328:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085330:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085332:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085334:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085336:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085338:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085338:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085340:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085340:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085342:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085342:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085344:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085344:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
2014-12-16 08:53:45.254 Kitematic[35252:1608181] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a19f10 h=--& v=--& V:[FI_TBrowserBackgroundView:0x7fa0b0a43ba0(0)]>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a1e120 h=-&- v=-&- V:|-(0)-[FI_TListScrollView:0x7fa0aa630c80]   (Names: '|':FI_TBrowserBackgroundView:0x7fa0b0a43ba0 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a1e0d0 h=-&- v=-&- V:[FI_TListScrollView:0x7fa0aa630c80]-(0)-|   (Names: '|':FI_TBrowserBackgroundView:0x7fa0b0a43ba0 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a521b0 h=-&- v=-&- V:[NSClipView:0x7fa0aa6308b0]-(15)-|   (Names: '|':FI_TListScrollView:0x7fa0aa630c80 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a51c40 h=-&- v=-&- V:|-(0)-[NSClipView:0x7fa0aa6308b0]   (Names: '|':FI_TListScrollView:0x7fa0aa630c80 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a4cdc0 h=-&- v=-&- V:[FI_TListView:0x7fa0aa6302b0]-(0)-|   (Names: '|':NSClipView:0x7fa0aa6308b0 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a423a0 h=-&- v=-&- V:|-(0)-[FI_TListView:0x7fa0aa6302b0]   (Names: '|':NSClipView:0x7fa0aa6308b0 )>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a4cdc0 h=-&- v=-&- V:[FI_TListView:0x7fa0aa6302b0]-(0)-|   (Names: '|':NSClipView:0x7fa0aa6308b0 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
2014-12-16 08:53:45.255 Kitematic[35252:1608181] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a19f10 h=--& v=--& V:[FI_TBrowserBackgroundView:0x7fa0b0a43ba0(0)]>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a1e120 h=-&- v=-&- V:|-(0)-[FI_TListScrollView:0x7fa0aa630c80]   (Names: '|':FI_TBrowserBackgroundView:0x7fa0b0a43ba0 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a1e0d0 h=-&- v=-&- V:[FI_TListScrollView:0x7fa0aa630c80]-(0)-|   (Names: '|':FI_TBrowserBackgroundView:0x7fa0b0a43ba0 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a521b0 h=-&- v=-&- V:[NSClipView:0x7fa0aa6308b0]-(15)-|   (Names: '|':FI_TListScrollView:0x7fa0aa630c80 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a51c40 h=-&- v=-&- V:|-(0)-[NSClipView:0x7fa0aa6308b0]   (Names: '|':FI_TListScrollView:0x7fa0aa630c80 )>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x7fa0b0a521b0 h=-&- v=-&- V:[NSClipView:0x7fa0aa6308b0]-(15)-|   (Names: '|':FI_TListScrollView:0x7fa0aa630c80 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
[35252:1216/085346:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085346:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085348:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085348:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085348:INFO:CONSOLE(163)] "From image: ubuntu:14.04", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (163)
[35252:1216/085350:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085350:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085352:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085352:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085354:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085354:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085356:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085356:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085358:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085358:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085400:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085400:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085402:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
[35252:1216/085402:INFO:CONSOLE(225)] "Error: connect ETIMEDOUT", source: http://localhost:60340/dc418e5a9662de3311a39175bc6c26e0b4173031.js (225)
^C
```

### Network Info
```
MacOS hterhanian$ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=3<RXCSUM,TXCSUM>
	inet6 ::1 prefixlen 128 
	inet 127.0.0.1 netmask 0xff000000 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=1<PERFORMNUD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=10b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV>
	ether 3c:07:54:15:5a:6a 
	inet6 fe80::3e07:54ff:fe15:5a6a%en0 prefixlen 64 scopeid 0x4 
	inet 192.168.32.4 netmask 0xffffff00 broadcast 192.168.32.255
	nd6 options=1<PERFORMNUD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 28:cf:da:e2:22:24 
	nd6 options=1<PERFORMNUD>
	media: autoselect (<unknown type>)
	status: inactive
fw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 4078
	lladdr a4:b1:97:ff:fe:31:0c:bc 
	nd6 options=1<PERFORMNUD>
	media: autoselect <full-duplex>
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether d2:00:13:10:cb:c0 
	media: autoselect <full-duplex>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 0a:cf:da:e2:22:24 
	media: autoselect
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 3e:07:54:51:cf:00 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 7 priority 0 path cost 0
	nd6 options=1<PERFORMNUD>
	media: <unknown type>
	status: inactive
vboxnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:00 
	inet 192.168.59.3 netmask 0xffffff00 broadcast 192.168.59.255
vboxnet1: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:01 
vboxnet3: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:03 
utun0: flags=80d1<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST> mtu 1399
	inet 10.50.35.171 --> 10.50.35.171 netmask 0xfffffe00 
	inet6 fe80::3e07:54ff:fe15:5a6a%utun0 prefixlen 64 scopeid 0xa 
	inet6 fe80::7843:3a9c:4b85:36f5%utun0 prefixlen 128 scopeid 0xa 
	nd6 options=1<PERFORMNUD>
```

**Comment by jeffdm** [comment] 2015-03-05 17:48
Sorry for the delay on this.

We've updated Kitematic 0.5 to use [machine](https://github.com/docker/machine). It's possible the conflict still exists but it's worth a try.

**Comment by varatep** [comment] 2015-03-17 15:34
Still getting this issue. Can confirm I have Cisco AnyConnect.

**Comment by jeffdm** [comment] 2015-06-01 20:44
Thanks for the update - sorry for hte delay.

This is a duplicate of #254 - closing

**Closed by jeffdm** 2015-06-01 20:44 UTC
Labels: bug
