### ISSUE TITLE
starting docker images, not showing in kitematic

### ISSUE THREAD

**Issue by b1alpha** [kitematic/kitematic#1156] opened 2015-10-29 23:20 UTC
kitematic is blank but im looking at a started docker image in my terminal window. weird

**Comment by FrenchBen** [comment] 2015-10-29 23:52
@b1alpha Can you provide steps to reproduce?
* Docker Toolbox version
* Docker image used
* Terminal command
* VM setup
etc.

**Comment by FrenchBen** [comment] 2015-11-05 00:24
Closing due to no details provided

**Closed by FrenchBen** 2015-11-05 00:24 UTC
