### ISSUE TITLE
Local Development - Cannot find electron v0.24.0 from GitHub

### ISSUE THREAD

**Issue by Elesant** [kitematic/kitematic#473] opened 2015-05-04 23:04 UTC
Running "npm start" for development

Cannot find electron v0.24.0 from GitHub
   at /Users/<redacted>/Work/git/<redacted>/kitematic/node_modules/gulp-download-electron/index.js:252:13
   at /Users/<redacted>/Work/git/<redacted>/kitematic/node_modules/async/lib/async.js:254:17
   at /Users/<redacted>/Work/git/<redacted>/kitematic/node_modules/async/lib/async.js:151:21
   at /Users/<redacted>/Work/git/<redacted>/kitematic/node_modules/async/lib/async.js:251:21
   at /Users/<redacted>/Work/git/<redacted>/kitematic/node_modules/async/lib/async.js:615:34
   at /Users/<redacted>/Work/git/<redacted>/kitematic/node_modules/gulp-download-electron/index.js:191:13
   at /Users/arunan/Work/git/<redacted>/kitematic/node_modules/gulp-download-electron/node_modules/github-releases/lib/github.js:33:18
   at Request._callback (/Users/<redacted>/Work/git/<redacted>/kitematic/node_modules/gulp-download-electron/node_modules/github-releases/lib/github.js:78:16)
   at self.callback (/Users/<redacted>/Work/git/<redacted>/kitematic/node_modules/gulp-download-electron/node_modules/github-releases/node_modules/request/request.js:129:22)
   at Request.emit (events.js:95:17)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/<redacted>/.nvm/v0.10.38/bin/npm" "start"
npm ERR! node v0.10.38
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE
npm ERR! Kitematic@0.5.23 start: `gulp`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the Kitematic@0.5.23 start script 'gulp'.
npm ERR! This is most likely a problem with the Kitematic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls Kitematic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/<redacted>/Work/git/<redacted>/kitematic/npm-debug.log

**Comment by jeffdm** [comment] 2015-05-04 23:12
Does this happen on a fresh clone or only if you pulled before the `electron` rename?

**Comment by jeffdm** [comment] 2015-05-04 23:13
We need to swap this `download-electron` package with an `npm` package

**Comment by Elesant** [comment] 2015-05-05 01:20
@jeffdm this happened from a fresh clone

**Comment by mchiang0610** [comment] 2015-05-21 06:05
@Elesant Just bought a new Mac, and works off a clean env.; tested with 2 other computers - cannot reproduce. 

Closing for now.

**Closed by mchiang0610** 2015-05-21 06:05 UTC
Labels: bug, tools
