### ISSUE TITLE
gluu

### ISSUE THREAD

**Issue by rashidniazi** [kitematic/kitematic#720] opened 2015-06-25 15:37 UTC
Hi 

I was interested in checking out the Gluu Docker cluster. However, when downloading it I recieve this error message. We're Sorry. There seem to be an error: Tag latest not found in repository nekbab/gluu. 

Not sure if this is expected or not...

**Comment by mchiang0610** [comment] 2015-06-26 00:04
@rashidniazi Which exact docker hub image is this? Does it have the latest tag?

**Comment by rashidniazi** [comment] 2015-06-26 21:22
Ouf not sure how to answer this. The image name when searching is "gluu" nekbab.

**Comment by jeffdm** [comment] 2015-07-02 01:34
This seems to be a duplicate of #720

Closing for now

**Closed by jeffdm** 2015-07-02 01:34 UTC

**Comment by fcjbispo** [comment] 2016-06-20 19:43
inspectig the existing tags in https://hub.docker.com/r/nekbab/gluu/tags/ i have pulled the v6 tag by issuing  docker pull nekbab/gluu:v6

But it provides no service when the image is started. It seems to be an empty centOS 6.5 image...
