### ISSUE TITLE
Please put a visible border around the app. 

### ISSUE THREAD

**Issue by tohagan** [kitematic/kitematic#1220] opened 2015-11-16 22:35 UTC
I'm finding that the Kitematic app window blends into the background of other windows with white backgrounds making it often difficult to identify that it's even there or where it begins and ends. This is particularly the case when (like most devs) I have a sea of windows open. The "no border" trick looks cool but UX is not so cool. Thanks for Kitematic!

**Comment by tohagan** [comment] 2015-11-16 22:37
A classic example of this is having Kitematic in the foreground with Chrome in the background.

**Comment by mikaoelitiana** [comment] 2015-11-17 07:00
In Mac, I have a border and shadow : 

![capture d ecran 2015-11-17 a 09 59 04](https://cloud.githubusercontent.com/assets/674667/11204654/fced551c-8d11-11e5-9b11-2cb4ca649255.png)

**Comment by FrenchBen** [comment] 2015-11-18 08:01
@mikaoelitiana It seems the issue is with Windows - For some reason the window manager doesn't add the proper border/shadow

**Comment by mikaoelitiana** [comment] 2015-11-18 08:10
I will try to reproduce that.

Le mer 18 nov. 2015 11:01, French Ben <notifications@github.com> a écrit :

> @mikaoelitiana <https://github.com/mikaoelitiana> It seems the issue is
> with Windows - For some reason the window manager doesn't add the proper
> border/shadow
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/issues/1220#issuecomment-157638607>
> .
>
-- 

Mika Andrianarijaona
+261340722394
http://mikaoelitiana.name

**Comment by FrenchBen** [comment] 2015-11-18 08:11
Merci @mikaoelitiana 

@tohagan What version of windows are you using?

**Comment by mikaoelitiana** [comment] 2015-11-18 08:16
De rien @FrenchBen :) . For me, I have a Win 10 x64 at home to test this issue.

**Comment by alexandrev** [comment] 2015-11-18 17:15
I have a border and shadow on Windows (W10, Build 10586) too:


![image](https://cloud.githubusercontent.com/assets/947041/11248218/3d3402ec-8e20-11e5-8983-440372b8661c.png)

**Comment by mikaoelitiana** [comment] 2015-11-19 12:07
Seems like it's a similar issue that #814

**Comment by tohagan** [comment] 2015-11-19 22:27
I have the same on Win7

**Comment by alexandrev** [comment] 2015-11-19 22:30
Could anyone paste a screenshot of the error you are identifying?

Thx!

-- Sent from my mobile phone. Please excuse any typo.

**Comment by tohagan** [comment] 2015-11-19 22:33
The screen shot from https://github.com/kitematic/kitematic/issues/814 matches the experience I'm having.  I think this issues is a duplicate.

**Comment by alexandrev** [comment] 2015-11-19 22:36
I agree with you, so I think we should close this issue and continue working together in the other forum.

**Comment by FrenchBen** [comment] 2015-11-23 19:53
Merging this with https://github.com/kitematic/kitematic/issues/1032

**Closed by FrenchBen** 2015-11-23 19:53 UTC
Labels: bug, exp/beginner, windows
